# Generated by Django 3.1.4 on 2021-01-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscription_plan_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(blank=True, max_length=500, null=True)),
                ('sms_count', models.CharField(blank=True, max_length=100, null=True)),
                ('per_sms_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cost', models.CharField(blank=True, max_length=500, null=True)),
                ('offered_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_in_rupee', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_in_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_plan', models.BooleanField(default=False, null=True)),
                ('business_category', models.CharField(blank=True, default='', max_length=20000, null=True)),
                ('merchant_name', models.CharField(blank=True, default='', max_length=20000, null=True)),
                ('customized_plan', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('customized_plan_for', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_plan', models.BooleanField(default=False, null=True)),
                ('addons', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
