# Generated by Django 3.1.4 on 2021-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0003_auto_20210127_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='discount_amount',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='is_discount',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
