# Generated by Django 3.1.4 on 2021-02-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0004_auto_20210224_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petrol_and_Parking_subscription_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_bill_cost', models.CharField(default='', max_length=200, null=True)),
                ('per_sms_cost', models.CharField(default='', max_length=200, null=True)),
                ('total_sms_cost', models.CharField(default='', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('is_discount', models.BooleanField(default=False, null=True)),
                ('category', models.CharField(default='', max_length=500, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions_Subscription_Plan_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sms', models.CharField(default='', max_length=200, null=True)),
                ('per_sms_cost', models.CharField(default='', max_length=200, null=True)),
                ('total_sms_cost', models.CharField(default='', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('is_discount', models.BooleanField(default=False, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='digital_cashmemo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='discount_in_percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='discount_in_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='plan_for',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='sms_cashmemo_cost',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='software_maintainance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='total_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
