# Generated by Django 3.1.4 on 2021-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0005_auto_20210226_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='min_recharge',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
