# Generated by Django 3.1.4 on 2021-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0007_auto_20210226_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='digital_cashmemo_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='discount_in_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='discount_in_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='sms_cashmemo_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='software_maintainance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='total_amount',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
