# Generated by Django 3.1.4 on 2021-05-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0009_auto_20210319_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrol_and_parking_subscription_model',
            name='subscription_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotions_subscription_plan_model',
            name='subscription_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
