# Generated by Django 3.1.4 on 2021-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0011_auto_20210528_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
