# Generated by Django 3.1.4 on 2021-05-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0012_auto_20210528_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscription_plan_details1',
        ),
    ]
