# Generated by Django 3.1.4 on 2021-05-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0013_delete_subscription_plan_details1'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions_subscription_plan_model',
            name='discount_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotions_subscription_plan_model',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promotions_subscription_plan_model',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
