# Generated by Django 3.1.4 on 2021-06-14 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0015_auto_20210528_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_on_plan_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_name', models.CharField(blank=True, max_length=500, null=True)),
                ('per_bill_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('per_receipt_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('per_cash_memo_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('per_digital_bill_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('per_digital_receipt_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('per_digital_cash_memo_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('recharge_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transactional_subscription_plan_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(blank=True, max_length=500, null=True)),
                ('total_sms', models.CharField(default='', max_length=200, null=True)),
                ('per_sms_cost', models.CharField(default='', max_length=200, null=True)),
                ('total_sms_cost', models.CharField(default='', max_length=200, null=True)),
                ('discount_in', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
