# Generated by Django 3.1.4 on 2021-06-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0016_add_on_plan_model_transactional_subscription_plan_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions_Subscription_Plan_Model',
            new_name='promotional_subscription_plan_model',
        ),
        migrations.DeleteModel(
            name='Petrol_and_Parking_subscription_Model',
        ),
    ]
