# Generated by Django 3.1.4 on 2021-06-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0017_auto_20210614_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='is_offer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
