# Generated by Django 3.1.4 on 2021-06-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0018_subscription_plan_details_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='suited_for',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
