# Generated by Django 3.1.4 on 2021-07-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0019_subscription_plan_details_suited_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='cost_for_users',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='number_of_users',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
