# Generated by Django 3.1.4 on 2021-07-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0020_auto_20210712_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='cost_for_users',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription_plan_details',
            name='number_of_users',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
