# Generated by Django 3.1.4 on 2021-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0022_auto_20210805_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='gs_amount',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
