# Generated by Django 3.1.4 on 2021-08-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0023_subscription_plan_details_gs_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_plan_details',
            old_name='gs_amount',
            new_name='gst_amount',
        ),
    ]
