# Generated by Django 3.1.4 on 2021-08-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0024_auto_20210805_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on_plan_model',
            name='gst_amount',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotional_subscription_plan_model',
            name='gst_amount',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactional_subscription_plan_model',
            name='gst_amount',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
