# Generated by Django 3.1.4 on 2021-08-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0025_auto_20210805_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on_plan_model',
            name='actual_total_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotional_subscription_plan_model',
            name='actual_total_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactional_subscription_plan_model',
            name='actual_total_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
