# Generated by Django 3.1.4 on 2021-08-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0026_auto_20210811_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='merchant_gst',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='merchant_number_of_users',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
