# Generated by Django 3.1.4 on 2021-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0027_auto_20210811_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_eight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_eleven',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_fifteen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_five',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_four',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_fourteen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_nine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_seven',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_six',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_ten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_thirteen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_three',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_twelve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
