# Generated by Django 3.1.4 on 2021-09-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0029_add_on_plan_model_actual_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_eighteen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_nineteen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_seventeen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_sixteen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_on_plan_model',
            name='recharge_amount_twenty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
