# Generated by Django 3.1.4 on 2021-12-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0030_auto_20210922_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotional_subscription_plan_model',
            name='business_category',
            field=models.CharField(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='promotional_subscription_plan_model',
            name='customized_plan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='promotional_subscription_plan_model',
            name='customized_plan_for',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotional_subscription_plan_model',
            name='merchant_name',
            field=models.CharField(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='promotional_subscription_plan_model',
            name='user_type',
            field=models.CharField(blank=True, default='all', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactional_subscription_plan_model',
            name='business_category',
            field=models.CharField(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='transactional_subscription_plan_model',
            name='customized_plan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transactional_subscription_plan_model',
            name='customized_plan_for',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactional_subscription_plan_model',
            name='merchant_name',
            field=models.CharField(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='transactional_subscription_plan_model',
            name='user_type',
            field=models.CharField(blank=True, default='all', max_length=100, null=True),
        ),
    ]
