# Generated by Django 3.1.4 on 2022-01-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0031_auto_20211221_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='loyalty_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
