# Generated by Django 3.1.4 on 2022-01-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0032_subscription_plan_details_loyalty_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_plan_details',
            old_name='loyalty_point',
            new_name='loyalty_point1',
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='loyalty_point2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription_plan_details',
            name='loyalty_point3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
