# Generated by Django 3.1.4 on 2022-01-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0033_auto_20220127_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_plan_details',
            old_name='loyalty_point1',
            new_name='loyalty_point',
        ),
        migrations.RemoveField(
            model_name='subscription_plan_details',
            name='loyalty_point2',
        ),
        migrations.RemoveField(
            model_name='subscription_plan_details',
            name='loyalty_point3',
        ),
    ]
