# Generated by Django 3.1.4 on 2022-02-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plan', '0034_auto_20220127_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan_details',
            name='per_url_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
