# Generated by Django 3.1.4 on 2021-03-01 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ads_for_merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_name', models.CharField(max_length=100)),
                ('redirect_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ads_image', models.ImageField(blank=True, default='', null=True, upload_to='ads_images')),
                ('default_ads', models.BooleanField(default=False, null=True)),
                ('active_ads', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ads_below_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_type', models.CharField(max_length=100)),
                ('ads_name', models.CharField(max_length=100)),
                ('redirect_url', models.CharField(blank=True, max_length=500, null=True)),
                ('default_ads', models.BooleanField(default=False, null=True)),
                ('business_name_value', models.CharField(max_length=2000)),
                ('ads_image', models.ImageField(blank=True, default='', null=True, upload_to='ads_images')),
                ('status', models.CharField(default='0', max_length=100)),
                ('disapproved_reason', models.CharField(default='', max_length=1000)),
                ('active_ads', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
