# Generated by Django 3.1.4 on 2021-03-02 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads_for_green_bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_name', models.CharField(max_length=100)),
                ('redirect_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ads_image', models.ImageField(blank=True, default='', null=True, upload_to='ads_images')),
                ('active_ads', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='ads_for_merchants',
            name='default_ads',
        ),
        migrations.AddField(
            model_name='ads_for_merchants',
            name='ads_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads_for_merchants',
            name='merchants_name_value',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
