# Generated by Django 3.1.4 on 2021-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20210302_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_for_merchants',
            name='business_category_value',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
