# Generated by Django 3.1.4 on 2021-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20210304_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_for_merchants',
            name='business_name_value',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
