# Generated by Django 3.1.4 on 2021-04-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_ads_for_merchants_business_name_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_for_merchants',
            name='end_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_for_merchants',
            name='schedule',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ads_for_merchants',
            name='start_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
