# Generated by Django 3.1.4 on 2021-05-31 13:16

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0006_auto_20210420_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulkMailSmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200, null=True)),
                ('smsheader', models.CharField(max_length=50, null=True)),
                ('template', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('o_sent_sms', models.BooleanField(default='0', null=True)),
                ('o_sent_mail', models.BooleanField(default='0', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bulkMailSmsSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.CharField(default='0', max_length=5, null=True)),
                ('sent_sms', models.BooleanField(default='0', null=True)),
                ('sent_mail', models.BooleanField(default='0', null=True)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.bulkmailsmsmodel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
