# Generated by Django 3.1.4 on 2021-06-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_bulkmailsmsmodel_bulkmailsmssent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmailsmsmodel',
            name='receiver_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
