# Generated by Django 3.1.4 on 2021-06-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_auto_20210616_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='m_first_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_below_bill',
            name='m_last_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_for_green_bills',
            name='m_first_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_for_green_bills',
            name='m_last_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
