# Generated by Django 3.1.4 on 2021-06-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0012_auto_20210628_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='third_party_amount',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
