# Generated by Django 3.1.4 on 2021-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0013_ads_below_bill_third_party_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_below_bill',
            name='third_party_amount',
            field=models.CharField(default='0', max_length=150, null=True),
        ),
    ]
