# Generated by Django 3.1.4 on 2021-07-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0014_auto_20210702_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='third_party_total_transaction',
            field=models.CharField(default='0', max_length=150, null=True),
        ),
    ]
