# Generated by Django 3.1.4 on 2021-08-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0015_ads_below_bill_third_party_total_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='received_cash_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
