# Generated by Django 3.1.4 on 2021-09-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merchantprofile_schedule_pdf_upload'),
        ('promotions', '0017_ads_below_bill_take_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='merchant_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile'),
        ),
    ]
