# Generated by Django 3.1.4 on 2021-10-13 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0056_userslogdetails'),
        ('promotions', '0019_auto_20211013_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_for_green_bills',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads_for_green_bills',
            name='merchant_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile'),
        ),
    ]
