# Generated by Django 3.1.4 on 2021-10-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0020_auto_20211013_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads_for_green_bills',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='ads_for_green_bills',
            name='merchant_business_id',
        ),
    ]
