# Generated by Django 3.1.4 on 2021-10-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0023_ads_below_bills_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='payment_amount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
