# Generated by Django 3.1.4 on 2021-10-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0024_ads_below_bill_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='payment_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_below_bill',
            name='payu_transaction_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ads_below_bill',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
