# Generated by Django 3.1.4 on 2021-10-24 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_merchantprofile_company_registration_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0026_auto_20211024_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionsPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.CharField(blank=True, max_length=1000, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('payu_transaction_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_done', models.BooleanField(default=False, null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('merchant_business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile')),
            ],
        ),
    ]
