# Generated by Django 3.1.4 on 2021-10-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0027_promotionspaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionspaymenthistory',
            name='ads_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
