# Generated by Django 3.1.4 on 2021-12-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0029_auto_20211102_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmailsmsmodel',
            name='campaign_name',
            field=models.CharField(default='Testing Campaign', max_length=500),
        ),
    ]
