# Generated by Django 3.1.4 on 2021-12-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0030_bulkmailsmsmodel_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='ads_below_bill_amount',
            field=models.CharField(default='0.00', max_length=100),
        ),
    ]
