# Generated by Django 3.1.4 on 2021-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpaymentlinks',
            name='transcation_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
