# Generated by Django 3.1.4 on 2021-06-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_ownerpaymentlinks_payu_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerpaymentlinks',
            name='transcation_id',
        ),
        migrations.AddField(
            model_name='ownerpaymentlinks',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownerpaymentlinks',
            name='payu_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
