# Generated by Django 3.1.4 on 2021-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210614_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpaymentlinks',
            name='payment_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
