# Generated by Django 3.1.4 on 2021-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_ownerpaymentlinks_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpaymentlinks',
            name='check_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
