# Generated by Django 3.1.4 on 2021-10-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_ownerpaymentlinks_check_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpaymentlinks',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
