# Generated by Django 3.1.4 on 2021-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_ownerpaymentlinks_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpaymentlinks',
            name='transaction_type',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
