# Generated by Django 3.1.4 on 2021-10-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20211024_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerpaymentlinks',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='ownerpaymentlinks',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
    ]
