# Generated by Django 3.1.4 on 2021-11-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20211116_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendpaymentmanually',
            old_name='payment_with',
            new_name='payment_for',
        ),
    ]
