from django.db import models

from django.conf import settings
User = settings.AUTH_USER_MODEL

from users.models import GreenBillUser, PartnerProfile
from category_and_tags.models import bill_category
from users.models import MerchantProfile
from django.utils import timezone

class CustomerBill(models.Model):
    user_id = models.CharField(max_length=100, blank=True)
    mobile_no = models.CharField(max_length=200, blank=True, default='')
    email = models.EmailField(max_length=100, blank= True, default='')
    bill = models.ImageField(null=True, blank=True, upload_to='customer_bill', default="")
    business_name = models.ForeignKey(MerchantProfile, default='', on_delete=models.CASCADE, blank=True, null=True)
    partner_business_name = models.ForeignKey(PartnerProfile, default='', on_delete=models.CASCADE, blank=True, null=True)
    customer_bill_category = models.ForeignKey(bill_category, default='', on_delete=models.CASCADE, blank=True, null=True)
    bill_amount = models.FloatField(default=0, null=True, blank=True)
    bill_date = models.DateField(default=timezone.now, null=True, )
    customer_added = models.BooleanField(default=False)
    bill_tags = models.CharField(max_length=20000, blank=True, null=True)
    remarks = models.CharField(max_length=200, blank=True, default='')
    custom_business_name = models.CharField(max_length=200, blank=True, default='')
    bill_url = models.CharField(max_length=200, blank=True, default='')
    created_at = models.DateTimeField(default=timezone.now, null=True,)
    green_points_earned = models.CharField(max_length=10, null=True, blank=True)
    seen_status = models.BooleanField(default=False)
    reject_status = models.BooleanField(default=False)
    reject_reason = models.CharField(max_length=500, blank=True, default='')
    invoice_no = models.CharField(max_length=200, blank=True, default='')
    rating = models.CharField(max_length=10, blank=True, default='')
    green_bill_transaction = models.BooleanField(default=False)
    green_bill_print_transaction = models.BooleanField(default=False)
    print_transaction = models.BooleanField(default=False)
    feedback_submit = models.BooleanField(default=False)
    feedback_question = models.CharField(max_length=1000, blank=True, default='')
    feedback_selected_option = models.CharField(max_length=1000, blank=True, default='')
    feedback_reply = models.CharField(max_length=150, blank=True, default='')
    payment_done = models.BooleanField(default=False)
    payment_date = models.DateTimeField(null=True, blank=True)
    transaction_id = models.CharField(max_length=100, null=True)
    payu_transaction_id = models.CharField(max_length=100, null=True)
    is_deleted = models.BooleanField(default=False)
    # created_at = models.DateTimeField(default=timezone.now, null=True,)
    stamp_id = models.CharField(max_length=100, null=True)
    is_favourite = models.BooleanField(default=False)
    exe_bill_type = models.CharField(max_length=100, null=True)
    greenbill_digital_bill = models.CharField(max_length=1000, blank=True, default='')
    greenbill_sms_bill = models.CharField(max_length=1000, blank=True, default='')
    is_ciprone = models.BooleanField(default=False)
    delete_bill = models.BooleanField(default=False)
    table_number = models.CharField(max_length=1000, blank=True, default='')
    waiter_name = models.CharField(max_length=1000, blank=True, default='')
    pax_number = models.CharField(max_length=1000, blank=True, default='')
    food_item_names = models.CharField(max_length=1000, blank=True, default='')
    food_quantity = models.CharField(max_length=1000, blank=True, default='')
    food_rate = models.CharField(max_length=1000, blank=True, default='')
    food_amount = models.CharField(max_length=1000, blank=True, default='')
    food_discount_parcentage = models.CharField(max_length=1000, blank=True, default='')
    service_charge = models.CharField(max_length=1000, blank=True, default='')
    bar_item_names = models.CharField(max_length=1000, blank=True, default='')
    bar_quantity = models.CharField(max_length=1000, blank=True, default='')
    bar_rate = models.CharField(max_length=1000, blank=True, default='')
    bar_amount = models.CharField(max_length=1000, blank=True, default='')
    bar_discount_percentage = models.CharField(max_length=1000, blank=True, default='')
    loyalty_points = models.CharField(max_length=1000, blank=True, default='')
    packaging = models.CharField(max_length=1000, blank=True, default='')
    delivery = models.CharField(max_length=1000, blank=True, default='')
    decoration = models.CharField(max_length=1000, blank=True, default='')
    is_checkoutpin = models.BooleanField(default=False)

    is_hebrone = models.BooleanField(default=False)
    extra_add = models.CharField(max_length=1000, blank=True, default='')
    particular = models.CharField(max_length=1000, blank=True, default='')
    cash = models.CharField(max_length=1000, blank=True, default='')
    card = models.CharField(max_length=1000, blank=True, default='')
    digital_pay = models.CharField(max_length=1000, blank=True, default='')

    discount_in_percentage = models.CharField(max_length=1000, blank=True, default='')
    cgst = models.CharField(max_length=1000, blank=True, default='')
    sgst = models.CharField(max_length=1000, blank=True, default='')
    igst = models.CharField(max_length=1000, blank=True, default='')
    hsn = models.CharField(max_length=1000, blank=True, default='')
    pack = models.CharField(max_length=1000, blank=True, default='')
    unit = models.CharField(max_length=1000, blank=True, default='')
    truck_no = models.CharField(max_length=1000, blank=True, default='')
    truck_driver = models.CharField(max_length=1000, blank=True, default='')
    truck_license_no = models.CharField(max_length=1000, blank=True, default='')
    transport_name = models.CharField(max_length=1000, blank=True, default='')
    pan_number = models.CharField(max_length=1000, blank=True, default='')
    maximum_retail_price = models.CharField(max_length=1000, blank=True, default='')
    amount = models.CharField(max_length=1000, blank=True, default='')
    total_amount = models.CharField(max_length=1000, blank=True, default='')
    net_amount = models.CharField(max_length=1000, blank=True, default='')

    sv_date1 = models.CharField(max_length=1000, blank=True, default='')
    sv_date2 = models.CharField(max_length=1000, blank=True, default='')
    nn1 = models.CharField(max_length=1000, blank=True, default='')
    sv_add1 = models.CharField(max_length=1000, blank=True, default='')
    sv_add2 = models.CharField(max_length=1000, blank=True, default='')
    sv_add3 = models.CharField(max_length=1000, blank=True, default='')
    sv_place = models.CharField(max_length=1000, blank=True, default='')
    sv_branch = models.CharField(max_length=1000, blank=True, default='')
    sv_pin = models.CharField(max_length=1000, blank=True, default='')
    sv_phone = models.CharField(max_length=1000, blank=True, default='')
    sv_mobile = models.CharField(max_length=1000, blank=True, default='')
    sv_account = models.CharField(max_length=1000, blank=True, default='')
    sv_banker = models.CharField(max_length=1000, blank=True, default='')
    sv_gst = models.CharField(max_length=1000, blank=True, default='')
    sv_flno = models.CharField(max_length=1000, blank=True, default='')
    sv_adhar = models.CharField(max_length=1000, blank=True, default='')
    sv_bslogan = models.CharField(max_length=1000, blank=True, default='')
    sv_entfmt = models.CharField(max_length=1000, blank=True, default='')
    sv_billfmt = models.CharField(max_length=1000, blank=True, default='')
    sv_mbill = models.CharField(max_length=1000, blank=True, default='')
    cust_fmcg = models.CharField(max_length=1000, blank=True, default='')
    sv_inv = models.CharField(max_length=1000, blank=True, default='')
    sv_items = models.CharField(max_length=1000, blank=True, default='')
    sv_defbunt = models.CharField(max_length=1000, blank=True, default='')
    sv_stkbill = models.CharField(max_length=1000, blank=True, default='')
    sv_slrwb = models.CharField(max_length=1000, blank=True, default='')
    sv_vline = models.CharField(max_length=1000, blank=True, default='')
    sv_balbill = models.CharField(max_length=1000, blank=True, default='')
    sv_items = models.CharField(max_length=1000, blank=True, default='')
    sv_lockr = models.CharField(max_length=1000, blank=True, default='')
    sv_rdext = models.CharField(max_length=1000, blank=True, default='')
    sv_crlimit = models.CharField(max_length=1000, blank=True, default='')
    sv_showrwb = models.CharField(max_length=1000, blank=True, default='')
    sv_cfcd = models.CharField(max_length=1000, blank=True, default='')
    sv_rpii = models.CharField(max_length=1000, blank=True, default='')
    sv_dos2usb = models.CharField(max_length=1000, blank=True, default='')
    sv_pl12 = models.CharField(max_length=1000, blank=True, default='')
    sv_kzero = models.CharField(max_length=1000, blank=True, default='')
    sv_smparty = models.CharField(max_length=1000, blank=True, default='')
    sv_remftr = models.CharField(max_length=1000, blank=True, default='')
    sv_copies = models.CharField(max_length=1000, blank=True, default='')
    sv_defpunt = models.CharField(max_length=1000, blank=True, default='')
    sv_updwb = models.CharField(max_length=1000, blank=True, default='')
    sv_tooltip = models.CharField(max_length=1000, blank=True, default='')
    sv_backup = models.CharField(max_length=1000, blank=True, default='')
    sv_cd = models.CharField(max_length=1000, blank=True, default='')
    sv_sch = models.CharField(max_length=1000, blank=True, default='')
    sv_roff = models.CharField(max_length=1000, blank=True, default='')
    sv_cash = models.CharField(max_length=1000, blank=True, default='')
    sv_frgt = models.CharField(max_length=1000, blank=True, default='')
    sv_hamali = models.CharField(max_length=1000, blank=True, default='')
    sv_tcsp = models.CharField(max_length=1000, blank=True, default='')
    sv_tcss = models.CharField(max_length=1000, blank=True, default='')
    sv_showwt = models.CharField(max_length=1000, blank=True, default='')
    sv_key = models.CharField(max_length=1000, blank=True, default='')
    sv_c01 = models.CharField(max_length=1000, blank=True, default='')
    sv_c02 = models.CharField(max_length=1000, blank=True, default='')
    sv_c03 = models.CharField(max_length=1000, blank=True, default='')
    sv_c04 = models.CharField(max_length=1000, blank=True, default='')
    sv_c05 = models.CharField(max_length=1000, blank=True, default='')
    sv_c06 = models.CharField(max_length=1000, blank=True, default='')
    pur_srno = models.CharField(max_length=1000, blank=True, default='')
    sale_srno = models.CharField(max_length=1000, blank=True, default='')
    sv_year = models.CharField(max_length=1000, blank=True, default='')
    sv_vrcr = models.CharField(max_length=1000, blank=True, default='')
    sv_vrcp = models.CharField(max_length=1000, blank=True, default='')
    sv_vrbr = models.CharField(max_length=1000, blank=True, default='')
    sv_vrbp = models.CharField(max_length=1000, blank=True, default='')
    sv_vrjb = models.CharField(max_length=1000, blank=True, default='')
    sv_vrmb = models.CharField(max_length=1000, blank=True, default='')
    sv_vrsb = models.CharField(max_length=1000, blank=True, default='')
    sv_vrpb = models.CharField(max_length=1000, blank=True, default='')
    sv_vroa = models.CharField(max_length=1000, blank=True, default='')
    sv_vrol = models.CharField(max_length=1000, blank=True, default='')
    sv_state = models.CharField(max_length=1000, blank=True, default='')
    sv_jury = models.CharField(max_length=1000, blank=True, default='')
    sv_defser = models.CharField(max_length=1000, blank=True, default='')
    sv_nn5 = models.CharField(max_length=1000, blank=True, default='')
    sv_dmprn = models.CharField(max_length=1000, blank=True, default='')
    sv_grid = models.CharField(max_length=1000, blank=True, default='')
    sv_mform = models.CharField(max_length=1000, blank=True, default='')
    sv_tform = models.CharField(max_length=1000, blank=True, default='')
    sv_isearch = models.CharField(max_length=1000, blank=True, default='')
    sv_compo = models.CharField(max_length=1000, blank=True, default='')
    sv_csale = models.CharField(max_length=1000, blank=True, default='')
    sv_rcprint = models.CharField(max_length=1000, blank=True, default='')
    sv_cpprint = models.CharField(max_length=1000, blank=True, default='')
    sv_brprint = models.CharField(max_length=1000, blank=True, default='')
    sv_bpprint = models.CharField(max_length=1000, blank=True, default='')
    sv_jbprint = models.CharField(max_length=1000, blank=True, default='')
    sv_logo = models.CharField(max_length=1000, blank=True, default='')
    sv_logofl = models.CharField(max_length=1000, blank=True, default='')
    sv_defdser = models.CharField(max_length=1000, blank=True, default='')
    sv_barcode = models.CharField(max_length=1000, blank=True, default='')
    sv_vrol = models.CharField(max_length=1000, blank=True, default='')
    sv_rlang = models.CharField(max_length=1000, blank=True, default='')
    sv_invbc = models.CharField(max_length=1000, blank=True, default='')
    sv_prlang = models.CharField(max_length=1000, blank=True, default='')
    sv_batch = models.CharField(max_length=1000, blank=True, default='')
    sv_rfront = models.CharField(max_length=1000, blank=True, default='')
    gst_date = models.CharField(max_length=1000, blank=True, default='')
    sv_picksch = models.CharField(max_length=1000, blank=True, default='')
    sv_lum = models.CharField(max_length=1000, blank=True, default='')
    sv_batch = models.CharField(max_length=1000, blank=True, default='')
    sv_spot = models.CharField(max_length=1000, blank=True, default='')
    sv_soft = models.CharField(max_length=1000, blank=True, default='')
    sv_btime = models.CharField(max_length=1000, blank=True, default='')
    sv_curdate = models.CharField(max_length=1000, blank=True, default='')
    sv_beatrate = models.CharField(max_length=1000, blank=True, default='')
    alpha_srch = models.CharField(max_length=1000, blank=True, default='')

    cdn_code = models.CharField(max_length=1000, blank=True, default='')
    mult_f = models.CharField(max_length=1000, blank=True, default='')
    trade = models.CharField(max_length=1000, blank=True, default='')
    bill_bb = models.CharField(max_length=1000, blank=True, default='')
    bill2 = models.CharField(max_length=1000, blank=True, default='')
    dm_no = models.CharField(max_length=1000, blank=True, default='')
    con_bill = models.CharField(max_length=1000, blank=True, default='')
    ad_bill = models.CharField(max_length=1000, blank=True, default='')
    bas10 = models.CharField(max_length=1000, blank=True, default='')
    amt10 = models.CharField(max_length=1000, blank=True, default='')
    sch10 = models.CharField(max_length=1000, blank=True, default='')
    dis10 = models.CharField(max_length=1000, blank=True, default='')
    cd10 = models.CharField(max_length=1000, blank=True, default='')
    net10 = models.CharField(max_length=1000, blank=True, default='')
    gd10 = models.CharField(max_length=1000, blank=True, default='')
    gst10 = models.CharField(max_length=1000, blank=True, default='')
    gr_code9 = models.CharField(max_length=1000, blank=True, default='')
    product = models.CharField(max_length=1000, blank=True, default='')
    product_i = models.CharField(max_length=1000, blank=True, default='')
    old_code = models.CharField(max_length=1000, blank=True, default='')
    spid = models.CharField(max_length=1000, blank=True, default='')
    h_code = models.CharField(max_length=1000, blank=True, default='')
    brand = models.CharField(max_length=1000, blank=True, default='')
    weight = models.CharField(max_length=1000, blank=True, default='')
    wt_unit = models.CharField(max_length=1000, blank=True, default='')
    it_weight = models.CharField(max_length=1000, blank=True, default='')
    qty_c = models.CharField(max_length=1000, blank=True, default='')
    unit_c = models.CharField(max_length=1000, blank=True, default='')
    pst1 = models.CharField(max_length=1000, blank=True, default='')
    mst1 = models.CharField(max_length=1000, blank=True, default='')
    roff = models.CharField(max_length=1000, blank=True, default='')
    t_qty = models.CharField(max_length=1000, blank=True, default='')
    freeval = models.CharField(max_length=1000, blank=True, default='')
    t_qty_c = models.CharField(max_length=1000, blank=True, default='')
    dis_c = models.CharField(max_length=1000, blank=True, default='')
    cd_c = models.CharField(max_length=1000, blank=True, default='')
    freeval = models.CharField(max_length=1000, blank=True, default='')
    bas10rate = models.CharField(max_length=1000, blank=True, default='')
    bas10amt = models.CharField(max_length=1000, blank=True, default='')
    sno_c = models.CharField(max_length=1000, blank=True, default='')
    gst_c = models.CharField(max_length=1000, blank=True, default='')
    rate_c = models.CharField(max_length=1000, blank=True, default='')
    bas10_c = models.CharField(max_length=1000, blank=True, default='')
    sch_c = models.CharField(max_length=1000, blank=True, default='')
    bas10sch = models.CharField(max_length=1000, blank=True, default='')
    bas10cd = models.CharField(max_length=1000, blank=True, default='')
    bas10dis = models.CharField(max_length=1000, blank=True, default='')
    bas10tle = models.CharField(max_length=1000, blank=True, default='')
    bas10net = models.CharField(max_length=1000, blank=True, default='')

    food_details = models.CharField(max_length=1000, blank=True, default='')
    bar_details = models.CharField(max_length=1000, blank=True, default='')

    series = models.CharField(max_length=1000, blank=True, default='')
    c_code = models.CharField(max_length=1000, blank=True, default='')
    br_code = models.CharField(max_length=1000, blank=True, default='')
    c_name = models.CharField(max_length=1000, blank=True, default='')  
    c_add1 = models.CharField(max_length=1000, blank=True, default='') 
    c_add2 = models.CharField(max_length=1000, blank=True, default='')  
    c_place = models.CharField(max_length=1000, blank=True, default='') 
    transfer = models.CharField(max_length=1000, blank=True, default='')
    trns_name = models.CharField(max_length=1000, blank=True, default='')
    bill_bb = models.CharField(max_length=1000, blank=True, default='')
    bill_dd = models.CharField(max_length=1000, blank=True, default='')
    bill2 = models.CharField(max_length=1000, blank=True, default='')   
    bill1 = models.CharField(max_length=1000, blank=True, default='')   
    n_b_amt = models.CharField(max_length=1000, blank=True, default='') 
    r_off = models.CharField(max_length=1000, blank=True, default='')   
    dm_ser = models.CharField(max_length=1000, blank=True, default='')  
    dm_no = models.CharField(max_length=1000, blank=True, default='')  
    con_date = models.CharField(max_length=1000, blank=True, default='')    
    con_bill = models.CharField(max_length=1000, blank=True, default='')    
    ad_series = models.CharField(max_length=1000, blank=True, default='')
    pst9 = models.CharField(max_length=1000, blank=True, default='')    
    c_cst = models.CharField(max_length=1000, blank=True, default='')   
    dvd_pay = models.CharField(max_length=1000, blank=True, default='') 
    finance = models.CharField(max_length=1000, blank=True, default='') 
    fn_code = models.CharField(max_length=1000, blank=True, default='') 
    dn_pay = models.CharField(max_length=1000, blank=True, default='')  
    fn_id = models.CharField(max_length=1000, blank=True, default='')   
    code_org = models.CharField(max_length=1000, blank=True, default='')    
    sm_org = models.CharField(max_length=1000, blank=True, default='')
    c_pan_no = models.CharField(max_length=1000, blank=True, default='')    
    fsaaino = models.CharField(max_length=1000, blank=True, default='') 
    n_name = models.CharField(max_length=1000, blank=True, default='')  
    hin_name = models.CharField(max_length=1000, blank=True, default='')   
    n_add1 = models.CharField(max_length=1000, blank=True, default='')  
    n_add2 = models.CharField(max_length=1000, blank=True, default='')  
    n_place = models.CharField(max_length=1000, blank=True, default='') 
    sman = models.CharField(max_length=1000, blank=True, default='')    
    smphone = models.CharField(max_length=1000, blank=True, default='')
    less_bsch = models.CharField(max_length=1000, blank=True, default='')
    food_mrp = models.CharField(max_length=1000,blank = True, default='')
    food_description = models.CharField(max_length=1000, blank=True, default='')
    bill_gross_amount = models.CharField(max_length=1000, blank=True, default='')
    bill_discount = models.CharField(max_length=1000, blank=True, default='')
    customer_name = models.CharField(max_length=1000, blank=True, default='')
    item_details = models.CharField(max_length=5000,blank=True, default='')
    

    def soft_delete(self):
        self.is_deleted = True
        self.save()



class InvoiceNumberSoftwareBill(models.Model):
    user_id = models.CharField(max_length=100, blank=True)
    m_user_id = models.CharField(max_length=100, blank=True)
    m_business_id = models.CharField(max_length=100)
    invoice_no = models.CharField(max_length=100)

class MerchantBill(models.Model):
    user_id = models.CharField(max_length=100, blank=True)
    mobile_no = models.CharField(max_length=200, blank=True, default='')
    email = models.EmailField(blank= True, default='')
    bill = models.ImageField(null=True, blank=True, upload_to='merchant_bill', default="")
    business_name = models.ForeignKey(MerchantProfile, default='', on_delete=models.CASCADE, blank=True, null=True)
    bill_received_business_name = models.CharField(max_length=200, blank=True, default='')
    customer_bill_category = models.ForeignKey(bill_category, default='', on_delete=models.CASCADE, blank=True, null=True)
    bill_amount = models.FloatField(default=0, null=True, blank=True)
    bill_date = models.DateField(default=timezone.now, null=True, )
    customer_added = models.BooleanField(default=False)
    bill_tags = models.CharField(max_length=20000, blank=True, null=True, default='')
    remarks = models.CharField(max_length=200, blank=True, default='')
    custom_business_name = models.CharField(max_length=200, blank=True, default='')
    bill_url = models.CharField(max_length=200, blank=True, default='')
    created_at = models.DateTimeField(default=timezone.now, null=True,)
    seen_status = models.BooleanField(default=False)
    reject_status = models.BooleanField(default=False)
    reject_reason = models.CharField(max_length=500, blank=True, default='')
    invoice_no = models.CharField(max_length=200, blank=True, default='')
    rating = models.CharField(max_length=10, blank=True, default='')
    green_bill_transaction = models.BooleanField(default=False)
    green_bill_print_transaction = models.BooleanField(default=False)
    print_transaction = models.BooleanField(default=False)
    feedback_submit = models.BooleanField(default=False)
    feedback_question = models.CharField(max_length=1000, blank=True, default='')
    feedback_selected_option = models.CharField(max_length=1000, blank=True, default='')
    payment_done = models.BooleanField(default=False)
    payment_date = models.DateTimeField(null=True, blank=True)
    transaction_id = models.CharField(max_length=100, null=True)
    payu_transaction_id = models.CharField(max_length=100, null=True)
    stamp_id = models.CharField(max_length=100, null=True)
    is_favourite = models.BooleanField(default=False)
    exe_bill_type = models.CharField(max_length=100, null=True)
    greenbill_digital_bill = models.CharField(max_length=1000, blank=True, default=False)
    greenbill_sms_bill = models.CharField(max_length=1000, blank=True, default=False)
    delete_bill = models.BooleanField(default=False)
    is_checkoutpin = models.BooleanField(default=False)

class DeviceId(models.Model):
    mobile_no = models.CharField(max_length=20)
    device_id = models.CharField(max_length=200)
    user_type = models.CharField(max_length=15)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

class ExePrintStatus(models.Model):
    business_id = models.CharField(max_length=20)
    bill = models.ImageField(null=True, blank=True, upload_to='customer_bill', default="")
    created_at = models.DateTimeField(default=timezone.now, null=True,)

class ExeImage(models.Model):
    business_id = models.CharField(max_length=20)
    bill = models.ImageField(null=True, blank=True, upload_to='customer_bill', default="")

