# Generated by Django 3.1.4 on 2021-01-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merchantprofile_m_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenbilluser',
            name='c_unique_id',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
