# Generated by Django 3.1.4 on 2021-01-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_and_tags', '0001_initial'),
        ('users', '0006_partnerprofile_p_commission_per_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenbilluser',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='greenbilluser',
            name='disable_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_category',
            field=models.CharField(choices=[('Software Partner', 'Software Partner'), ('Marketing Partner', 'Marketing Partner')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='p_business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category_and_tags.business_category'),
        ),
        migrations.DeleteModel(
            name='PartnerCategory',
        ),
    ]
