# Generated by Django 3.1.4 on 2021-01-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210121_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='p_business_category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
