# Generated by Django 3.1.4 on 2021-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merchant_users_m_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='p_business_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
