# Generated by Django 3.1.4 on 2021-02-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merchantprofile_m_vat_tin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenbilluser',
            name='merchant_referral_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
