# Generated by Django 3.1.4 on 2021-03-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_greenbilluser_merchant_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='m_cancel_bank_cheque_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='cancel_bank_cheque_photo'),
        ),
    ]
