# Generated by Django 3.1.4 on 2021-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210311_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='m_other_document1',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='m_other_document2',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
