# Generated by Django 3.1.4 on 2021-03-27 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210311_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='m_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
