# Generated by Django 3.1.4 on 2021-05-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210424_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenbilluser',
            name='customer_referral_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='greenbilluser',
            name='c_unique_id',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
