# Generated by Django 3.1.4 on 2021-05-19 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210508_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='disable_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='disapprove_reason',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='m_latest_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='disable_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='disapprove_reason',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_latest_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
