# Generated by Django 3.1.4 on 2021-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210520_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='p_business_category',
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='m_latest_account',
            field=models.BooleanField(default=True),
        ),
    ]
