# Generated by Django 3.1.4 on 2021-06-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_and_tags', '0002_bill_category_icon'),
        ('users', '0023_auto_20210602_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='p_business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category_and_tags.business_category'),
        ),
    ]
