# Generated by Django 3.1.4 on 2021-06-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_partnerprofile_p_business_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='p_latest_account',
        ),
    ]
