# Generated by Django 3.1.4 on 2021-06-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_partnerprofile_p_latest_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenbilluser',
            name='c_used_referral_code',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='greenbilluser',
            name='m_used_referral_code',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
