# Generated by Django 3.1.4 on 2021-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210605_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='by_partner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
