# Generated by Django 3.1.4 on 2021-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_greenbilluser_disable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='address_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='address_proof'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='address_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='address_proof'),
        ),
    ]
