# Generated by Django 3.1.4 on 2021-07-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210701_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantUniqueIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_unique_id', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerUniqueIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_unique_id', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='greenbilluser',
            name='m_unique_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='greenbilluser',
            name='p_unique_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
