# Generated by Django 3.1.4 on 2021-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210701_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenbilluser',
            name='email_verification_url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='greenbilluser',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
