# Generated by Django 3.1.4 on 2021-07-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210701_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='m_PAN_card',
            field=models.FileField(blank=True, default='', null=True, upload_to='merchant_PAN_card'),
        ),
    ]
