# Generated by Django 3.1.4 on 2021-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_merchantprofile_m_pan_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='m_pan_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
