# Generated by Django 3.1.4 on 2021-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210715_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='m_unique_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
