# Generated by Django 3.1.4 on 2021-07-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_merchantprofile_m_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='m_unique_id',
        ),
    ]
