# Generated by Django 3.1.4 on 2021-08-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_merchantprofile_m_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='merchant_commission',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
