# Generated by Django 3.1.4 on 2021-08-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_partnerprofile_merchant_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='address_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='merchant_address_proof'),
        ),
    ]
