# Generated by Django 3.1.4 on 2021-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20210817_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='merchant_authorised_sign',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
