# Generated by Django 3.1.4 on 2021-09-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_merchantprofile_merchant_authorised_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='m_address_bank_account',
            field=models.ImageField(blank=True, default='', null=True, upload_to='merchant_adress_bank_acount'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='m_bank_account_entry',
            field=models.ImageField(blank=True, default='', null=True, upload_to='merchant_bank_aacount_entity'),
        ),
    ]
