# Generated by Django 3.1.4 on 2021-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210905_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='m_bank_adress',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='m_bank_entity',
            field=models.CharField(default='', max_length=500),
        ),
    ]
