# Generated by Django 3.1.4 on 2021-09-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20210906_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='m_bank_adress_account',
            new_name='Address_Entity_Bank_Account',
        ),
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='m_bank_entity_account',
            new_name='Name_Entity_Account',
        ),
    ]
