# Generated by Django 3.1.4 on 2021-09-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20210906_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='Entity_Account_m',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='Entity_Bank_Account_m',
            field=models.CharField(default='', max_length=500),
        ),
    ]
