# Generated by Django 3.1.4 on 2021-09-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merchantprofile_schedule_pdf_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='commission_per_bill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='commission_per_sms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
