# Generated by Django 3.1.4 on 2021-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20210922_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='commission_per_bill',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='commission_per_sms',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='m_website_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_website_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
