# Generated by Django 3.1.4 on 2021-09-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20210927_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='m_website_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='p_website_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
