# Generated by Django 3.1.4 on 2021-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20210927_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='p_commission_per_digital_bill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_commission_per_sms_bill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
