# Generated by Django 3.1.4 on 2021-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20210930_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='m_business_name_for_billing',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_business_name_for_billing',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
