# Generated by Django 3.1.4 on 2021-10-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20211001_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='m_billing_email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='m_billing_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
