# Generated by Django 3.1.4 on 2021-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20211008_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='m_billing_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
