# Generated by Django 3.1.4 on 2021-10-09 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_merchantprofile_m_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserslogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('module_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('action', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
