# Generated by Django 3.1.4 on 2021-10-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_userslogdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='company_registration_certificate',
            field=models.ImageField(blank=True, default='', null=True, upload_to='merchant_registration_certificate'),
        ),
    ]
