# Generated by Django 3.1.4 on 2021-10-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_merchantprofile_company_registration_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='schedule_pdf_upload',
            field=models.ImageField(blank=True, default='', null=True, upload_to='payu_schedule_upload_pdf'),
        ),
    ]
