# Generated by Django 3.1.4 on 2021-11-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20211029_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='p_billing_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_billing_email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_billing_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
