# Generated by Django 3.1.4 on 2021-11-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20211101_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='p_adress_account_entity',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_bank_account_entity',
            field=models.CharField(default='', max_length=500),
        ),
    ]
