# Generated by Django 3.1.4 on 2021-11-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20211101_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='p_company_registration_certificate',
            field=models.ImageField(blank=True, default='', null=True, upload_to='partner_company_registration_certificate'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_pan_legal_entity',
            field=models.ImageField(blank=True, default='', null=True, upload_to='partner_legal_entity'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='p_signature_proof',
            field=models.ImageField(blank=True, default='', null=True, upload_to='partner_signature_proof'),
        ),
    ]
