# Generated by Django 3.1.4 on 2021-11-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20211101_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='schedule_pdf_upload',
            field=models.ImageField(blank=True, default='', null=True, upload_to='payu_schedule_upload_pdf'),
        ),
    ]
