# Generated by Django 3.1.4 on 2021-11-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20211102_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='p_payu_schedule_upload',
            field=models.ImageField(blank=True, default='', null=True, upload_to='partner_payu_upload'),
        ),
    ]
