# Generated by Django 3.1.4 on 2021-11-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_partnerprofile_p_payu_schedule_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='schedule_pdf_upload',
        ),
    ]
