# Generated by Django 3.1.4 on 2021-11-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_remove_merchantprofile_schedule_pdf_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='schedule_pdf_upload',
            field=models.ImageField(blank=True, default='', null=True, upload_to='merchant_business_logo'),
        ),
    ]
