# Generated by Django 3.1.4 on 2021-12-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20211230_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='subscription_count',
            field=models.IntegerField(default=0),
        ),
    ]
