# Generated by Django 3.1.4 on 2022-01-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_merchantprofile_subscription_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='bothplan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='loyalty_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='membership',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
