# Generated by Django 3.1.4 on 2022-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20220125_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='loyalty_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
