# Generated by Django 3.1.4 on 2021-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareOfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_offer_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/')),
                ('offer_url', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
