# Generated by Django 3.1.4 on 2021-06-24 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share_web_offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareoffermodel',
            name='active_web_offer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='shareoffermodel',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
