# Generated by Django 3.1.4 on 2021-09-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merchantprofile_schedule_pdf_upload'),
        ('share_web_offer', '0002_auto_20210624_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareoffermodel',
            name='merchant_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile'),
        ),
    ]
