# Generated by Django 3.1.7 on 2021-06-02 06:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemOwnerCouponModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_business_id', models.CharField(default='', max_length=100, null=True)),
                ('user_id', models.CharField(default='', max_length=100, null=True)),
                ('coupon_id', models.CharField(default='', max_length=100, null=True)),
                ('coupon_name', models.CharField(default='', max_length=100, null=True)),
                ('coupon_code', models.CharField(default='', max_length=100, null=True)),
                ('green_point', models.CharField(default='', max_length=100, null=True)),
                ('coupon_redeem_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 2, 11, 57, 13, 956577))),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerCouponModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_business_id', models.CharField(default='', max_length=100, null=True)),
                ('coupon_name', models.CharField(default='', max_length=100, null=True)),
                ('valid_from', models.DateField(default='', null=True)),
                ('valid_through', models.DateField(default='', null=True)),
                ('coupon_code', models.CharField(default='', max_length=100, null=True)),
                ('coupon_value', models.CharField(default='', max_length=100, null=True)),
                ('green_point', models.CharField(default='', max_length=100, null=True)),
                ('coupon_logo', models.ImageField(default='', null=True, upload_to='Coupon_Logo/')),
                ('coupon_redeem', models.CharField(default='0', max_length=10, null=True)),
                ('coupon_caption', models.CharField(default='', max_length=50, null=True)),
                ('coupon_background_color', models.CharField(default='', max_length=100, null=True)),
                ('coupon_valid_for_user', models.CharField(default='', max_length=100, null=True)),
                ('amount_in', models.CharField(default='', max_length=100, null=True)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
