# Generated by Django 3.1.4 on 2021-06-05 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_coupon', '0002_auto_20210602_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownercouponmodel',
            name='coupon_logo',
        ),
        migrations.AlterField(
            model_name='redeemownercouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 5, 13, 39, 33, 256048)),
        ),
    ]
