# Generated by Django 3.1.4 on 2021-07-06 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_coupon', '0004_auto_20210701_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercouponmodel',
            name='add_merchant_name_by_owner',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='redeemownercouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 6, 13, 11, 20, 559136)),
        ),
    ]
