# Generated by Django 3.1.4 on 2021-03-17 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('m_user_id', models.CharField(blank=True, max_length=100)),
                ('m_business_id', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLotPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_business_id', models.CharField(max_length=100, null=True)),
                ('m_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('vehical_no', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SaveParkingLotBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('m_user_id', models.CharField(blank=True, max_length=100)),
                ('m_business_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(max_length=200)),
                ('exit_gate', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker_name', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_hours_charges', models.CharField(default='', max_length=100, null=True)),
                ('c_unique_id', models.CharField(default='', max_length=20, null=True)),
                ('bill_file', models.ImageField(blank=True, default='', null=True, upload_to='customer_bill')),
                ('exit_check', models.BooleanField(default=False)),
                ('out_date', models.CharField(blank=True, max_length=100, null=True)),
                ('out_time', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_url', models.CharField(blank=True, default='', max_length=200)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('bill_category_id', models.CharField(default='27', max_length=100)),
                ('bill_tags', models.CharField(blank=True, default='', max_length=20000, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('bill_flag', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, default='', max_length=10)),
                ('is_checkoutpin', models.BooleanField(default=False)),
                ('manage_space', models.BooleanField(default=False)),
                ('charges_by', models.CharField(blank=True, default='', max_length=100)),
                ('flag_update_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
