# Generated by Django 3.1.4 on 2021-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0003_parkinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglog',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
