# Generated by Django 3.1.4 on 2021-04-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0006_auto_20210327_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='for_additional_hours',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='for_hours',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
