# Generated by Django 3.1.4 on 2021-04-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0007_auto_20210403_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglotpass',
            name='company_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='parkinglotpass',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='parkinglotpass',
            name='pass_type',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
