# Generated by Django 3.1.4 on 2021-04-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0008_auto_20210403_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
    ]
