# Generated by Django 3.1.4 on 2021-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0009_saveparkinglotbill_is_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='pass_company_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
