# Generated by Django 3.1.4 on 2021-04-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0011_auto_20210405_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='pass_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
