# Generated by Django 3.1.4 on 2021-04-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0012_saveparkinglotbill_pass_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglotpass',
            name='user_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
