# Generated by Django 3.1.4 on 2021-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0013_parkinglotpass_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='green_points_earned',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
