# Generated by Django 3.1.4 on 2021-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0015_auto_20210426_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='seen_status',
            field=models.BooleanField(default=True),
        ),
    ]
