# Generated by Django 3.1.4 on 2021-06-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0018_auto_20210601_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveparkinglotbill',
            name='bill_category_id',
            field=models.CharField(default='27', max_length=100, null=True),
        ),
    ]
