# Generated by Django 3.1.4 on 2021-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0020_auto_20210616_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='payu_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
