# Generated by Django 3.1.4 on 2021-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0021_auto_20210619_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
