# Generated by Django 3.1.4 on 2021-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0024_auto_20211020_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveparkinglotbill',
            name='delete_bill',
            field=models.BooleanField(default=False),
        ),
    ]
