# Generated by Django 3.1.4 on 2021-11-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0025_saveparkinglotbill_delete_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveparkinglotbill',
            name='is_checkoutpin',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
