# Generated by Django 3.1.4 on 2021-11-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_apis', '0026_auto_20211117_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveparkinglotbill',
            name='is_checkoutpin',
            field=models.BooleanField(default=False),
        ),
    ]
