# Generated by Django 3.1.6 on 2021-02-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20210208_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponmodel',
            name='greenbill',
        ),
        migrations.RemoveField(
            model_name='couponmodel',
            name='mycustomer',
        ),
    ]
