# Generated by Django 3.1.6 on 2021-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20210208_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='customer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='greenbill',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
