# Generated by Django 3.1.6 on 2021-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20210208_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='category',
            field=models.CharField(choices=[('', ''), ('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default='Select Category', max_length=50, verbose_name='Select Category'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
