# Generated by Django 3.1.6 on 2021-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_auto_20210209_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='agegroup',
            field=models.CharField(max_length=50),
        ),
    ]
