# Generated by Django 3.1.6 on 2021-02-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_auto_20210209_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Select Category'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
