# Generated by Django 3.1.4 on 2021-02-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_auto_20210218_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='coupon_logo',
            field=models.ImageField(default='', null=True, upload_to='Coupon_Logo/'),
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='coupon_redeem',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
