# Generated by Django 3.1.4 on 2021-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20210222_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='coupon_caption',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
