# Generated by Django 3.1.4 on 2021-03-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_couponmodel_coupon_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='coupon_background_color',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
