# Generated by Django 3.1.4 on 2021-03-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0013_couponmodel_coupon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='coupon_user',
            new_name='coupon_valid_for_user',
        ),
    ]
