# Generated by Django 3.1.4 on 2021-03-25 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0018_auto_20210325_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='merchant_business_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='redeemcouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 13, 50, 33, 913618)),
        ),
    ]
