# Generated by Django 3.1.4 on 2021-03-25 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0019_auto_20210325_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcouponmodel',
            name='merchant_business_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='redeemcouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 15, 33, 52, 946525)),
        ),
    ]
