# Generated by Django 3.1.4 on 2021-07-01 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0022_auto_20210327_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='customer_area',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='customer_city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='customer_state',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='redeemcouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 1, 16, 53, 0, 819418)),
        ),
    ]
