# Generated by Django 3.1.4 on 2021-07-01 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0023_auto_20210701_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='cout',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='redeemcouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 1, 18, 54, 58, 734879)),
        ),
    ]
