# Generated by Django 3.1.4 on 2021-07-06 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0024_auto_20210701_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='add_merchant_name_by_owner',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='redeemcouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 6, 12, 47, 51, 958393)),
        ),
    ]
