# Generated by Django 3.1.4 on 2021-07-09 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0025_auto_20210706_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='coupon_panel',
            field=models.CharField(default='merchant', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='owner_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='redeemcouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 10, 12, 7, 532610)),
        ),
    ]
