# Generated by Django 3.1.4 on 2021-08-27 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0026_auto_20210709_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcouponmodel',
            name='coupon_redeem_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 27, 15, 15, 51, 427976)),
        ),
    ]
