# Generated by Django 3.1.4 on 2020-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_category_name', models.CharField(default='', max_length=200)),
                ('bill_category_description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='bill_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_tags_name', models.CharField(default='', max_length=200)),
                ('bill_tags_description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='business_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_category_name', models.CharField(default='', max_length=200)),
                ('business_category_description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
