# Generated by Django 3.1.4 on 2021-07-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_info', '0003_bulkmailsmspartnermodel_sent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmailsmspartnermodel',
            name='transactional',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
