# Generated by Django 3.1.4 on 2021-09-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_info', '0007_auto_20210809_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMonthlyCommision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_mobile_no', models.CharField(blank=True, max_length=500, null=True)),
                ('month', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
