# Generated by Django 3.1.4 on 2021-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_info', '0008_partnermonthlycommision'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermonthlycommision',
            name='year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
