# Generated by Django 3.1.4 on 2021-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_info', '0009_partnermonthlycommision_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvfileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, default='', null=True, upload_to='merchant_address_proof')),
            ],
        ),
    ]
