# Generated by Django 3.1.4 on 2021-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_info', '0010_csvfileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_excel_file', models.FileField(blank=True, default='', null=True, upload_to='merchant_address_proof')),
            ],
        ),
    ]
