# Generated by Django 3.1.4 on 2021-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_notice_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onwernoticeboard',
            name='receiver_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
