# Generated by Django 3.1.4 on 2021-01-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0002_merchantparkinglotspace_merchantpetrolpump'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpetrolpump',
            name='product_availability',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
