# Generated by Django 3.1.4 on 2021-01-20 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_setting', '0003_merchantpetrolpump_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantparkinglotspace',
            old_name='spaces',
            new_name='spaces_count',
        ),
        migrations.RemoveField(
            model_name='merchantparkinglotspace',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='merchantparkinglotspace',
            name='charges_by',
        ),
        migrations.AddField(
            model_name='merchantparkinglotspace',
            name='vehicle_type_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchantparkinglotspace',
            name='entry_gate',
            field=models.BooleanField(max_length=1),
        ),
        migrations.AlterField(
            model_name='merchantparkinglotspace',
            name='exit_gate',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='merchantparkinglotspace',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MerchantParkingSpaceCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_business_id', models.CharField(max_length=100)),
                ('vehicle_type_id', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('charges_by', models.CharField(choices=[('One Time', 'One Time'), ('Hourly', 'Hourly')], max_length=100)),
                ('charges', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantParkingAddVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_business_id', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('2 Wheeler', '2 Wheeler'), ('3 Wheeler', '3 Wheeler'), ('4 Wheeler', '4 Wheeler')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
