# Generated by Django 3.1.4 on 2021-02-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_setting', '0004_auto_20210120_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantparkingspacecharges',
            name='charges_by',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Hourly', 'Hourly'), ('Additional Hours', 'Additional Hours')], max_length=100),
        ),
        migrations.CreateModel(
            name='petrol_pump_app_setting_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_bill', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('footer_text', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='parking_app_setting_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_bill', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('footer_text', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
