# Generated by Django 3.1.4 on 2021-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0005_auto_20210205_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantparkingspacecharges',
            name='additional_hours_charges',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchantparkingspacecharges',
            name='charges_by',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Hourly', 'Hourly')], max_length=100),
        ),
    ]
