# Generated by Django 3.1.4 on 2021-02-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0006_auto_20210205_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_app_setting_model',
            name='entry_gate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parking_app_setting_model',
            name='exit_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merchantparkingaddvehicle',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
    ]
