# Generated by Django 3.1.4 on 2021-02-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0011_auto_20210227_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petrol_pump_app_setting_model',
            name='header_text2',
        ),
        migrations.RemoveField(
            model_name='petrol_pump_app_setting_model',
            name='header_text3',
        ),
    ]
