# Generated by Django 3.1.4 on 2021-03-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0014_auto_20210301_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_app_setting_model',
            name='pay_bill_at_exit_gate',
            field=models.BooleanField(default=False),
        ),
    ]
