# Generated by Django 3.1.4 on 2021-03-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0015_parking_app_setting_model_pay_bill_at_exit_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantparkingspacecharges',
            name='half_yearly_charges',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchantparkingspacecharges',
            name='monthly_charges',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchantparkingspacecharges',
            name='per_visit_charges',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchantparkingspacecharges',
            name='quarterly_charges',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchantparkingspacecharges',
            name='yearly_charges',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
