# Generated by Django 3.1.4 on 2021-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0016_auto_20210312_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_app_setting_model',
            name='manage_space',
            field=models.BooleanField(default=False),
        ),
    ]
