# Generated by Django 3.1.4 on 2021-03-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0018_auto_20210313_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantparkinglotpasscharges',
            name='vehicle_type',
        ),
    ]
