# Generated by Django 3.1.4 on 2021-03-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210311_1843'),
        ('merchant_setting', '0019_remove_merchantparkinglotpasscharges_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_app_setting_model',
            name='merchant_bussiness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.merchantprofile'),
        ),
    ]
