# Generated by Django 3.1.4 on 2021-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0021_petrol_pump_app_setting_model_merchant_bussiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpetrolpump',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
