# Generated by Django 3.1.4 on 2021-03-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0022_auto_20210317_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantparkingspacecharges',
            name='for_additional_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantparkingspacecharges',
            name='for_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchantparkingspacecharges',
            name='charges_by',
            field=models.CharField(choices=[('One Time', 'One Time')], max_length=100),
        ),
    ]
