# Generated by Django 3.1.4 on 2021-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0027_auto_20210405_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantparkinglotspace',
            name='entry_gate',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='merchantparkinglotspace',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
