# Generated by Django 3.1.4 on 2021-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0028_auto_20210405_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantparkinglotpasscharges',
            name='pass_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchantparkinglotpasscharges',
            name='vehicle_type_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
