# Generated by Django 3.1.4 on 2021-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0029_auto_20210412_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantparkinglotpasscharges',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
