# Generated by Django 3.1.4 on 2021-04-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0030_merchantparkinglotpasscharges_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantparkinglotpasscharges',
            name='charges',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
