# Generated by Django 3.1.4 on 2021-04-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0031_merchantparkinglotpasscharges_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantparkinglotpasscharges',
            name='half_yearly_charges',
        ),
        migrations.RemoveField(
            model_name='merchantparkinglotpasscharges',
            name='monthly_charges',
        ),
        migrations.RemoveField(
            model_name='merchantparkinglotpasscharges',
            name='per_visit_charges',
        ),
        migrations.RemoveField(
            model_name='merchantparkinglotpasscharges',
            name='quarterly_charges',
        ),
        migrations.RemoveField(
            model_name='merchantparkinglotpasscharges',
            name='yearly_charges',
        ),
    ]
