# Generated by Django 3.1.4 on 2021-07-22 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0033_merchantpaymentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_app_setting_model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='petrol_pump_app_setting_model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
