# Generated by Django 3.1.4 on 2022-01-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20220125_1110'),
        ('merchant_setting', '0034_auto_20210722_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteBillsByDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_days', models.CharField(max_length=100)),
                ('delete_from', models.CharField(max_length=100)),
                ('m_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.merchantprofile')),
            ],
        ),
    ]
