# Generated by Django 3.1.4 on 2022-01-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0036_deletebillsbydays_merchant_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteBillsByDays',
        ),
    ]
