# Generated by Django 3.1.4 on 2022-01-25 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_setting', '0037_delete_deletebillsbydays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Bills_By_Days_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_days', models.CharField(max_length=100)),
                ('deleted_from', models.CharField(max_length=100)),
                ('m_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
