# Generated by Django 3.1.4 on 2022-03-04 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0039_auto_20220304_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted_bills_by_days_setting',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
