# Generated by Django 3.1.4 on 2022-03-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0041_auto_20220312_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentsetting',
            name='option',
            field=models.CharField(default='', max_length=100),
        ),
    ]
