# Generated by Django 3.1.4 on 2022-03-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_setting', '0042_merchantpaymentsetting_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpaymentsetting',
            name='payu_key',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchantpaymentsetting',
            name='payu_salt',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='merchantpaymentsetting',
            name='upi_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
