# Generated by Django 3.1.4 on 2021-05-23 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_notice_model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
