# Generated by Django 3.1.4 on 2021-05-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_notice', '0002_merchant_notice_model_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant_notice_model',
            old_name='mer_id',
            new_name='owner_id',
        ),
    ]
