# Generated by Django 3.1.4 on 2021-06-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_notice', '0003_auto_20210523_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_notice_model',
            name='receiver_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
