# Generated by Django 3.1.4 on 2021-10-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sharebillmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=150, null=True)),
                ('db_table', models.CharField(max_length=150, null=True)),
                ('bill_id', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
