# Generated by Django 3.1.4 on 2021-01-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantEnquiryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=50, null=True)),
                ('bissiness_name', models.CharField(default='', max_length=50, null=True)),
                ('contact_no', models.CharField(max_length=12)),
                ('email_id', models.EmailField(default='', max_length=254, null=True)),
                ('intrested_in', models.CharField(default='', max_length=20, null=True)),
                ('comments', models.CharField(default='', max_length=20000, null=True)),
                ('enquary_status', models.CharField(default='Active', max_length=15, null=True)),
                ('mer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
