# Generated by Django 3.1.4 on 2021-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_enquiry', '0003_auto_20210208_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantenquirymodel',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
