# Generated by Django 3.1.4 on 2021-07-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_enquiry', '0004_merchantenquirymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantenquirymodel',
            name='assign_company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
