# Generated by Django 3.1.4 on 2021-07-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_enquiry', '0005_merchantenquirymodel_assign_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantenquirymodel',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
