# Generated by Django 3.1.4 on 2022-04-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_enquiry', '0006_merchantenquirymodel_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantenquirymodel',
            name='email_id',
            field=models.EmailField(default='', max_length=100, null=True),
        ),
    ]
