# Generated by Django 3.1.4 on 2021-01-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_apis', '0002_delete_deviceidmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerQR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_email', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
