# Generated by Django 3.1.4 on 2021-01-29 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_apis', '0004_customerqr_qr_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerqr',
            name='c_email',
        ),
        migrations.RemoveField(
            model_name='customerqr',
            name='c_name',
        ),
        migrations.RemoveField(
            model_name='customerqr',
            name='qr_type',
        ),
        migrations.AddField(
            model_name='customerqr',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customerqr',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
