# Generated by Django 3.1.4 on 2021-07-03 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_update', '0002_auto_20210701_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='unread_system_updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, null=True)),
                ('notification_id', models.IntegerField(max_length=20, null=True)),
                ('group_customer', models.BooleanField(default=False, null=True)),
                ('group_merchant', models.BooleanField(default=False, null=True)),
                ('group_partner', models.BooleanField(default=False, null=True)),
                ('group_petrol', models.BooleanField(default=False, null=True)),
                ('group_parking', models.BooleanField(default=False, null=True)),
                ('read_status', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
