# Generated by Django 3.1.4 on 2021-02-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Memos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_name', models.CharField(default='', max_length=100, null=True)),
                ('header_text', models.CharField(default='', max_length=500, null=True)),
                ('footer_text', models.CharField(default='', max_length=500, null=True)),
                ('stamp_image', models.ImageField(upload_to='cash_memo')),
                ('fav_color', models.CharField(default='', max_length=50, null=True)),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
