# Generated by Django 3.1.4 on 2021-03-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_memo_receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipts_name', models.CharField(default='', max_length=100, null=True)),
                ('header_text', models.CharField(default='', max_length=500, null=True)),
                ('footer_text', models.CharField(default='', max_length=500, null=True)),
                ('stamp_image', models.ImageField(upload_to='cash_memo')),
                ('fav_color', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cash_memos',
            name='users_id',
        ),
    ]
