# Generated by Django 3.1.4 on 2021-05-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20210518_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
