# Generated by Django 3.1.4 on 2021-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210518_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(max_length=120, null='True'),
            preserve_default='True',
        ),
    ]
