# Generated by Django 3.1.4 on 2021-01-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0002_invoicenumberpetrolpump'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
