# Generated by Django 3.1.4 on 2021-01-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0003_auto_20210124_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepetrolpumpbill',
            name='m_user',
        ),
        migrations.AddField(
            model_name='invoicenumberpetrolpump',
            name='m_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='m_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicenumberpetrolpump',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
