# Generated by Django 3.1.4 on 2021-01-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0004_auto_20210126_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepetrolpumpbill',
            name='c_email',
        ),
        migrations.RemoveField(
            model_name='savepetrolpumpbill',
            name='c_name',
        ),
    ]
