# Generated by Django 3.1.4 on 2021-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0005_auto_20210129_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='worker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
