# Generated by Django 3.1.4 on 2021-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0007_auto_20210209_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='addon_product_cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='addon_product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='addon_product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='total_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
