# Generated by Django 3.1.4 on 2021-02-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0008_auto_20210211_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='bill_category_id',
            field=models.CharField(default='26', max_length=100),
        ),
    ]
