# Generated by Django 3.1.4 on 2021-02-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0010_auto_20210219_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepetrolpumpbill',
            name='total_amount',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
