# Generated by Django 3.1.4 on 2021-02-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0012_auto_20210219_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='addon_quantity',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='nozzle_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
