# Generated by Django 3.1.4 on 2021-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0014_savepetrolpumpbill_bill_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
