# Generated by Django 3.1.4 on 2021-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0015_savepetrolpumpbill_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='is_checkoutpin',
            field=models.BooleanField(default=False),
        ),
    ]
