# Generated by Django 3.1.4 on 2021-03-17 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0016_savepetrolpumpbill_is_checkoutpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='flag_update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
