# Generated by Django 3.1.4 on 2021-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0019_petrollog'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='reason_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='savepetrolpumpbill',
            name='flag_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
