# Generated by Django 3.1.4 on 2021-04-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0020_auto_20210327_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='green_points_earned',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
