# Generated by Django 3.1.4 on 2021-04-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0021_savepetrolpumpbill_green_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepetrolpumpbill',
            name='green_points_earned',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
