# Generated by Django 3.1.4 on 2021-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0022_auto_20210426_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='seen_status',
            field=models.BooleanField(default=True),
        ),
    ]
