# Generated by Django 3.1.4 on 2021-05-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0023_savepetrolpumpbill_seen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepetrolpumpbill',
            name='seen_status',
            field=models.BooleanField(default=False),
        ),
    ]
