# Generated by Django 3.1.4 on 2021-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0027_auto_20210616_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='payu_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
