# Generated by Django 3.1.4 on 2021-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0029_savepetrolpumpbill_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
