# Generated by Django 3.1.4 on 2021-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0030_savepetrolpumpbill_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='greenbill_digital_bill',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='greenbill_sms_bill',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
