# Generated by Django 3.1.4 on 2021-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0031_auto_20211020_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='delete_bill',
            field=models.BooleanField(default=False),
        ),
    ]
