# Generated by Django 3.1.4 on 2021-11-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0032_savepetrolpumpbill_delete_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepetrolpumpbill',
            name='p_business_ids',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
