# Generated by Django 3.1.4 on 2021-11-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0033_savepetrolpumpbill_p_business_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepetrolpumpbill',
            name='p_business_ids',
        ),
    ]
