# Generated by Django 3.1.4 on 2021-11-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_pump_apis', '0034_remove_savepetrolpumpbill_p_business_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepetrolpumpbill',
            name='is_checkoutpin',
            field=models.CharField(blank=True, default='False', max_length=1000),
        ),
    ]
