# Generated by Django 3.1.4 on 2021-01-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_points', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenpointsmodel',
            old_name='green_ponits_count',
            new_name='green_points_count',
        ),
    ]
