# Generated by Django 3.1.4 on 2021-03-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_points', '0002_auto_20210122_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpointsmodel',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
