# Generated by Django 3.1.5 on 2021-03-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_cashmemo_design', '0002_cash_memo_design_model_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_memo_design_model',
            name='number_of_copy',
            field=models.IntegerField(null=True),
        ),
    ]
