# Generated by Django 3.1.5 on 2021-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_cashmemo_design', '0003_cash_memo_design_model_number_of_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_memo_design_model',
            name='number_of_copy',
        ),
        migrations.AddField(
            model_name='cash_memo_design_model',
            name='comments',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
