# Generated by Django 3.1.5 on 2021-03-05 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_cashmemo_design', '0005_remove_cash_memo_design_model_merchant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_memo_design_model',
            name='merchant_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.greenbilluser'),
            preserve_default=False,
        ),
    ]
