# Generated by Django 3.1.4 on 2021-05-04 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_auto_20210424_1126'),
        ('merchant_cashmemo_design', '0006_cash_memo_design_model_merchant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceiptDetailsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(default='', max_length=120, null=True)),
                ('mobile_number', models.CharField(max_length=10, null=True)),
                ('receipt_url', models.CharField(default='', max_length=200, null=True)),
                ('cash_received_from', models.CharField(default='', max_length=120, null=True)),
                ('rs', models.CharField(default='', max_length=120, null=True)),
                ('amount_for', models.CharField(default='', max_length=120, null=True)),
                ('date', models.DateField(default='', null=True)),
                ('template_choice', models.CharField(default='', max_length=20, null=True)),
                ('total', models.CharField(default='', max_length=50, null=True)),
                ('grand_total', models.CharField(default='', max_length=120, null=True)),
                ('merchant_business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile')),
                ('merchant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCashMemoDetailModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_no', models.CharField(default='', max_length=120, null=True)),
                ('name', models.CharField(default='', max_length=120, null=True)),
                ('address', models.CharField(default='', max_length=120, null=True)),
                ('mobile_number', models.CharField(default='', max_length=10, null=True)),
                ('date', models.DateField(default='', null=True)),
                ('memo_url', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(default='', max_length=120, null=True)),
                ('quantity', models.CharField(default='', max_length=120, null=True)),
                ('rate', models.CharField(default='', max_length=120, null=True)),
                ('amount', models.CharField(default='', max_length=120, null=True)),
                ('template_choice', models.CharField(default='', max_length=20, null=True)),
                ('total', models.CharField(default='', max_length=50, null=True)),
                ('total_in_words', models.CharField(default='', max_length=120, null=True)),
                ('merchant_business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile')),
                ('merchant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
