# Generated by Django 3.1.4 on 2021-05-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_cashmemo_design', '0007_customercashmemodetailmodels_customerreceiptdetailsmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercashmemodetailmodels',
            name='authorised_sign',
            field=models.FileField(blank=True, default='', null=True, upload_to='memo_authorised_sign'),
        ),
        migrations.AddField(
            model_name='customercashmemodetailmodels',
            name='term_and_condition1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customercashmemodetailmodels',
            name='term_and_condition2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customercashmemodetailmodels',
            name='term_and_condition3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='authorised_sign',
            field=models.FileField(blank=True, default='', null=True, upload_to='receipt_authorised_sign'),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='received_in_cash',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='received_in_cheque',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='received_in_other',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='term_and_condition1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='term_and_condition2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='term_and_condition3',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
