# Generated by Django 3.1.4 on 2021-06-08 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_cashmemo_design', '0008_auto_20210531_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_memo_design_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cash_memo_design_model',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
