# Generated by Django 3.1.4 on 2021-07-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_cashmemo_design', '0009_auto_20210608_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_memo_design_model',
            name='notes',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
