# Generated by Django 3.1.4 on 2021-09-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merchantprofile_schedule_pdf_upload'),
        ('merchant_cashmemo_design', '0011_save_template_for_cashmemo_save_template_for_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_memo_design_model',
            name='merchant_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile'),
        ),
    ]
