# Generated by Django 3.1.4 on 2021-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_cashmemo_design', '0014_save_stamp_for_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercashmemodetailmodels',
            name='stamp_last_record',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='stamp_last_record',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
