# Generated by Django 3.1.4 on 2021-09-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_cashmemo_design', '0015_auto_20210913_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercashmemodetailmodels',
            name='is_stamp_type',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customerreceiptdetailsmodels',
            name='is_stamp_type',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
