# Generated by Django 3.1.4 on 2021-06-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpaymentlinks',
            name='payu_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerpaymentlinks',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
