# Generated by Django 3.1.4 on 2021-01-21 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Info_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_first_name', models.CharField(default=0, max_length=100, null=True)),
                ('cust_last_lname', models.CharField(default=0, max_length=100, null=True)),
                ('cust_email', models.EmailField(default=0, max_length=254, null=True)),
                ('cust_mobile_num', models.CharField(default=0, max_length=12, null=True)),
                ('customer_area', models.CharField(default=0, max_length=500, null=True)),
                ('customer_pin_code', models.IntegerField(default=0, null=True)),
                ('mer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
