# Generated by Django 3.1.4 on 2021-05-22 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info_model',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
