# Generated by Django 3.1.4 on 2021-06-16 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_info', '0002_customer_info_model_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info_model',
            name='par_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_info_model',
            name='mer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL),
        ),
    ]
