# Generated by Django 3.1.4 on 2021-06-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0003_auto_20210616_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info_model',
            old_name='par_id',
            new_name='per_id',
        ),
    ]
