# Generated by Django 3.1.4 on 2021-09-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merchantprofile_schedule_pdf_upload'),
        ('customer_info', '0004_auto_20210616_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info_model',
            name='merchant_business_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_name', to='users.merchantprofile'),
        ),
    ]
