# Generated by Django 3.1.4 on 2020-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='o_business_stamp',
            field=models.ImageField(blank=True, default='', null=True, upload_to='business_stamp'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='o_digital_signature',
            field=models.ImageField(blank=True, default='', null=True, upload_to='digital_signature'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='o_business_logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='business_logos'),
        ),
    ]
