# Generated by Django 3.1.4 on 2021-04-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201229_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='CIN_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='CIN_certificate'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='GSTIN_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='GSTIN_certificate'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='aadhaar_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='alternate_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='alternate_mobile_number',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='area',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='bank_IFSC_code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='bank_account_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='bank_branch',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='bank_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='cancelled_cheque_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='cancelled_cheque_certificate'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='cin',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='city',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='district',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='gstin',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='pan_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='pin_code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='state',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='tin_vat_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='udyog_adhar_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='udyog_adhar_certificate'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='business_code',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='business_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='mobile_no',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='user_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
