# Generated by Django 3.1.4 on 2021-06-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='address_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='address_proof'),
        ),
    ]
