# Generated by Django 3.1.4 on 2021-08-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_generalsetting_address_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='CIN_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='owner_CIN_certificate'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='GSTIN_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='owner_GSTIN_certificate'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='address_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='owner_address_proof'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='cancelled_cheque_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='owner_cancelled_cheque_certificate'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='udyog_adhar_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='owner_udyog_adhar_certificate'),
        ),
    ]
