# Generated by Django 3.1.4 on 2021-03-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_greenbilluser_merchant_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_designs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('rating', models.BooleanField(default=False)),
                ('rating_text', models.CharField(default='', max_length=200)),
                ('rating_emoji', models.CharField(default='', max_length=200)),
                ('facebook', models.BooleanField(default=False)),
                ('facebook_url', models.CharField(default='', max_length=1000)),
                ('youtube', models.BooleanField(default=False)),
                ('youtube_url', models.CharField(default='', max_length=1000)),
                ('twitter', models.BooleanField(default=False)),
                ('twitter_url', models.CharField(default='', max_length=1000)),
                ('instagram', models.BooleanField(default=False)),
                ('instagram_url', models.CharField(default='', max_length=1000)),
                ('ads_below_bill', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('website', models.BooleanField(default=False)),
                ('website_url', models.CharField(default='', max_length=1000)),
                ('map', models.BooleanField(default=False)),
                ('map_link', models.CharField(default='', max_length=1000)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('terms_url', models.CharField(default='', max_length=1000)),
                ('footer_logo', models.BooleanField(default=False)),
                ('merchant_business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile')),
            ],
        ),
    ]
