# Generated by Django 3.1.4 on 2021-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0002_auto_20210312_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_designs',
            name='apple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_designs',
            name='apple_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
