# Generated by Django 3.1.4 on 2021-06-03 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill_design', '0003_auto_20210317_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorised_sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.FileField(blank=True, null=True, upload_to='authorised_sign')),
                ('selection', models.CharField(max_length=5, null=True)),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
