# Generated by Django 3.1.4 on 2021-08-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0005_bill_designs_pay_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_designs',
            name='swiggy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_designs',
            name='swiggy_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='bill_designs',
            name='zomato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_designs',
            name='zomato_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
