# Generated by Django 3.1.4 on 2021-12-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0006_auto_20210806_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_designs',
            name='tripadvisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_designs',
            name='tripadvisor_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
