# Generated by Django 3.1.4 on 2022-03-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0008_auto_20220225_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_pdf_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_image', models.FileField(blank=True, null=True, upload_to='temp_pdf')),
                ('image_con', models.FileField(blank=True, null=True, upload_to='temp_img')),
            ],
        ),
    ]
