# Generated by Django 3.1.4 on 2022-03-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0009_temp_pdf_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_pdf_check',
            name='image_con',
            field=models.FileField(blank=True, null=True, upload_to='temp1'),
        ),
        migrations.AlterField(
            model_name='temp_pdf_check',
            name='pdf_image',
            field=models.FileField(blank=True, null=True, upload_to='temp1'),
        ),
    ]
