# Generated by Django 3.1.4 on 2022-03-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0011_contact_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_card',
            name='card_desc',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
