# Generated by Django 3.1.4 on 2022-03-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0012_contact_card_card_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_card',
            name='card_photo',
            field=models.FileField(blank=True, null=True, upload_to='card_pic/'),
        ),
    ]
