# Generated by Django 3.1.4 on 2022-03-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0013_auto_20220328_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_card',
            name='card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
    ]
