# Generated by Django 3.1.4 on 2022-04-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0015_auto_20220331_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_card',
            name='about_us',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='address_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='address_book_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='alternate_mobile',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='bussiness_time',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='email_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='msg_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='qrcode_photo',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='temp_choice',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
