# Generated by Django 3.1.4 on 2022-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0017_auto_20220406_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_card',
            name='acc_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='acco_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='gstin_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='ifsc_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='pan_card',
            field=models.CharField(default='', max_length=15),
        ),
    ]
