# Generated by Django 3.1.4 on 2022-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0019_auto_20220415_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=100)),
                ('rating', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact_card',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contact_card',
            name='rating',
        ),
    ]
