# Generated by Django 3.1.4 on 2022-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0020_auto_20220415_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_card',
            name='client1',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='client2',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='client3',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='client4',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='client5',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
        migrations.AddField(
            model_name='contact_card',
            name='client6',
            field=models.ImageField(blank=True, null=True, upload_to='card_pic/'),
        ),
    ]
