# Generated by Django 3.1.4 on 2022-04-16 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0021_auto_20220415_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
