# Generated by Django 3.1.4 on 2022-04-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0022_card_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_card',
            name='sharecount',
            field=models.IntegerField(null=True),
        ),
    ]
