# Generated by Django 3.1.4 on 2022-04-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0025_auto_20220416_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_card',
            name='view',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
