# Generated by Django 3.1.4 on 2022-04-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_merchantprofile_loyalty_point'),
        ('bill_design', '0026_contact_card_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_feedback',
            name='merchant_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile'),
        ),
    ]
