# Generated by Django 3.1.4 on 2021-06-09 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_feedback_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_business_id', models.CharField(default='', max_length=200)),
                ('for_rating', models.CharField(default='', max_length=10)),
                ('question', models.CharField(default='', max_length=1000)),
                ('option_1', models.CharField(default='', max_length=500)),
                ('option_2', models.CharField(default='', max_length=500)),
                ('option_3', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
