# Generated by Django 3.1.4 on 2021-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_designs_owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('rating', models.BooleanField(default=False)),
                ('rating_text', models.CharField(default='', max_length=200)),
                ('rating_emoji', models.CharField(default='', max_length=200)),
                ('facebook', models.BooleanField(default=False)),
                ('facebook_url', models.CharField(default='', max_length=1000)),
                ('youtube', models.BooleanField(default=False)),
                ('youtube_url', models.CharField(default='', max_length=1000)),
                ('twitter', models.BooleanField(default=False)),
                ('twitter_url', models.CharField(default='', max_length=1000)),
                ('instagram', models.BooleanField(default=False)),
                ('instagram_url', models.CharField(default='', max_length=1000)),
                ('ads_below_bill', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('website', models.BooleanField(default=False)),
                ('website_url', models.CharField(default='', max_length=1000)),
                ('map', models.BooleanField(default=False)),
                ('map_link', models.CharField(default='', max_length=1000)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('terms_url', models.CharField(default='', max_length=1000)),
                ('footer_logo', models.BooleanField(default=False)),
                ('linkedin', models.BooleanField(default=False)),
                ('linkedin_url', models.CharField(default='', max_length=1000)),
                ('skype', models.BooleanField(default=False)),
                ('skype_url', models.CharField(default='', max_length=1000)),
                ('google', models.BooleanField(default=False)),
                ('google_url', models.CharField(default='', max_length=1000)),
                ('pinterest', models.BooleanField(default=False)),
                ('pinterest_url', models.CharField(default='', max_length=1000)),
                ('snapchat', models.BooleanField(default=False)),
                ('snapchat_url', models.CharField(default='', max_length=1000)),
                ('android', models.BooleanField(default=False)),
                ('android_url', models.CharField(default='', max_length=1000)),
                ('apple', models.BooleanField(default=False)),
                ('apple_url', models.CharField(default='', max_length=1000)),
                ('pay_link', models.BooleanField(default=False)),
            ],
        ),
    ]
