# Generated by Django 3.1.4 on 2021-08-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_bill_design', '0002_auto_20210626_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_designs_owner',
            name='swiggy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_designs_owner',
            name='swiggy_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='bill_designs_owner',
            name='zomato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_designs_owner',
            name='zomato_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
