# Generated by Django 3.1.4 on 2022-04-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_bill_design', '0003_auto_20210806_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_designs_owner',
            name='indiamart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_designs_owner',
            name='indiamart_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='bill_designs_owner',
            name='justdail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_designs_owner',
            name='justdail_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
