# Generated by Django 3.1.4 on 2020-12-10 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=500)),
                ('view', models.CharField(blank=True, max_length=500)),
                ('add', models.CharField(blank=True, max_length=500)),
                ('edit', models.CharField(blank=True, max_length=500)),
                ('delete', models.CharField(blank=True, max_length=500)),
                ('view_permission', models.CharField(blank=True, max_length=500)),
                ('add_permission', models.CharField(blank=True, max_length=500, null=True)),
                ('edit_permission', models.CharField(blank=True, max_length=500, null=True)),
                ('delete_permission', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='merchant_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='merchant_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('role_description', models.CharField(blank=True, max_length=500, null=True)),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='merchant_userrole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant_role.merchant_role')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='merchant_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_permission', models.CharField(blank=True, max_length=500, null=True)),
                ('add_permission', models.CharField(blank=True, max_length=500, null=True)),
                ('edit_permission', models.CharField(blank=True, max_length=500, null=True)),
                ('delete_permission', models.CharField(blank=True, max_length=500, null=True)),
                ('feature_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant_role.merchant_feature')),
                ('merchant_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant_role.merchant_module')),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant_role.merchant_role')),
            ],
        ),
        migrations.AddField(
            model_name='merchant_feature',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant_role.merchant_module'),
        ),
    ]
