# Generated by Django 3.1.4 on 2021-09-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merchantprofile_schedule_pdf_upload'),
        ('merchant_role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_role',
            name='merchant_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile'),
        ),
    ]
