# Generated by Django 3.1.4 on 2021-05-20 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_auto_20210519_1536'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='offer_link',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='stamp_image',
        ),
        migrations.AddField(
            model_name='offermodel',
            name='Offer_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='disapproved_reason',
            field=models.CharField(default='Not Applicable', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='merchant_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='merchant_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='offer_business_category',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='offer_caption',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='offer_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='offer_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='status',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='valid_through',
            field=models.DateField(blank=True, null=True),
        ),
    ]
