# Generated by Django 3.1.4 on 2021-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20210520_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='offer_panel',
            field=models.CharField(default='merchant', max_length=100),
        ),
    ]
