# Generated by Django 3.1.4 on 2021-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offermodel_offer_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='check_business_category',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='merchant_business_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='o_business_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
