# Generated by Django 3.1.4 on 2021-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210529_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='customer_city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='merchant_area',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='merchant_city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='merchant_district',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='merchant_state',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='offer_amount',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
