# Generated by Django 3.1.4 on 2021-06-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20210605_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='cout',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
