# Generated by Django 3.1.4 on 2021-07-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offermodel_cout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='offer_amount',
            field=models.CharField(default='0', max_length=150, null=True),
        ),
    ]
