# Generated by Django 3.1.4 on 2021-08-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_offermodel_offer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='customer_merchant_count',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
