# Generated by Django 3.1.4 on 2021-10-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_offermodel_customer_merchant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='partner_area',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='partner_city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='partner_state',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
