from django.db import models
from django.utils import timezone

# Create your models here.


class SaveParkingLotBill(models.Model):
    user_id = models.CharField(max_length=100, blank=True)
    m_user_id = models.CharField(max_length=100, blank=True)
    m_business_id = models.CharField(max_length=100, null=True)
    p_business_id = models.CharField(max_length=100, null=True)
    mobile_no = models.CharField(max_length=100)
    vehicle_type = models.CharField(max_length=100)
    vehicle_type_id = models.CharField(max_length=100, null=True, blank=True)
    vehicle_number = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)
    date = models.CharField(max_length=100, null=True, blank=True)
    time = models.CharField(max_length=100, null=True, blank=True)
    invoice_no = models.CharField(max_length=200)
    exit_gate = models.CharField(max_length=50, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    worker_name = models.CharField(max_length=100, blank=True, null=True)
    additional_hours_charges = models.CharField(max_length=100, null=True, default='')
    c_unique_id = models.CharField(max_length=20, null=True, default='')
    bill_file = models.ImageField(null=True, blank=True, upload_to='customer_bill', default="")
    exit_check = models.BooleanField(default=False)
    out_date = models.CharField(max_length=100, null=True, blank=True)
    out_time = models.CharField(max_length=100, null=True, blank=True)
    bill_url = models.CharField(max_length=200, blank=True, default='')
    duration = models.CharField(max_length=200, null=True, blank=True)
    bill_category_id = models.CharField(max_length=100, default="27", null=True)
    bill_tags = models.CharField(max_length=20000, blank=True, null=True, default='')
    remarks = models.CharField(max_length=200, blank=True, default='')
    bill_flag = models.BooleanField(default=False)
    rating = models.CharField(max_length=10, blank=True, default='')
    is_checkoutpin = models.BooleanField(default=False)
    manage_space = models.BooleanField(default=False)
    charges_by = models.CharField(max_length=100, blank=True, default='')
    flag_update_at = models.DateTimeField(default=timezone.now)
    flag_by = models.CharField(max_length=100, blank=True)
    reason_id = models.CharField(max_length=100, blank=True)
    reason = models.CharField(max_length=500, blank=True)
    for_hours = models.CharField(max_length=500, blank=True)
    for_additional_hours = models.CharField(max_length=500, blank=True)
    is_pass = models.BooleanField(default=False)
    pass_company_name = models.CharField(max_length=500, blank=True)
    pass_id = models.CharField(max_length=500, blank=True)
    # green_points_earned = models.CharField(max_length=500, default="1")
    green_points_earned = models.CharField(max_length=10, null=True, blank=True)
    seen_status = models.BooleanField(default=False)
    reject_status = models.BooleanField(default=False)
    reject_reason = models.CharField(max_length=500, blank=True, default='')
    payment_done = models.BooleanField(default=False)
    payment_date = models.DateTimeField(null=True, blank=True)
    transaction_id = models.CharField(max_length=100, null=True)
    payu_transaction_id = models.CharField(max_length=100, null=True)
    is_deleted = models.BooleanField(default=False)
    is_favourite = models.BooleanField(default=False)
    greenbill_digital_bill = models.CharField(max_length=1000, blank=True, default='')
    greenbill_sms_bill = models.CharField(max_length=1000, blank=True, default='')
    delete_bill = models.BooleanField(default=False)

    def soft_delete(self):
        self.is_deleted = True
        self.save()


class InvoiceNumberParkingLot(models.Model):
    user_id = models.CharField(max_length=100, blank=True)
    m_user_id = models.CharField(max_length=100, blank=True)
    m_business_id = models.CharField(max_length=100)
    invoice_no = models.CharField(max_length=100)

class ParkingLotPass(models.Model):
    m_business_id = models.CharField(max_length=100, null=True)
    user_id = models.CharField(max_length=500, null=True)
    m_user_id = models.CharField(max_length=100, null=True, blank=True)
    mobile_no = models.CharField(max_length=100, null=True)
    amount = models.CharField(max_length=100, null=True)
    valid_from = models.DateField(blank=True, null=True)
    valid_to = models.DateField(blank=True, null=True)
    comments = models.CharField(max_length=500, blank=True, default="")
    created_at = models.DateTimeField(default=timezone.now, null=True)
    vehical_no = models.CharField(max_length=500, blank=True, default="")
    pass_type = models.CharField(max_length=500, blank=True, default="")
    company_id = models.CharField(max_length=500, blank=True, default="")
    company_name = models.CharField(max_length=500, blank=True, default="")
    vehicle_type = models.CharField(max_length=500, blank=True, default="")
    vehicle_type_id = models.CharField(max_length=500, blank=True, default="")

class ParkingLog(models.Model):
    user_id = models.CharField(max_length=100, blank=True)
    login_at = models.DateTimeField(default=timezone.now)
    logout_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now, null=True)