# Generated by Django 3.1.4 on 2021-01-29 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription_plan', '0003_auto_20210127_1318'),
        ('my_subscription', '0005_auto_20210129_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(blank=True, max_length=500, null=True)),
                ('per_bill_cost', models.FloatField(blank=True, null=True)),
                ('digital_bill', models.FloatField(blank=True, null=True)),
                ('is_subscription_plan', models.BooleanField(default=False, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription_plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription_plan.subscription_plan_details')),
            ],
        ),
        migrations.CreateModel(
            name='merchant_subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_bill_cost', models.FloatField(blank=True, null=True)),
                ('digital_bill', models.FloatField(blank=True, null=True)),
                ('total_amount_avilable', models.FloatField(blank=True, null=True)),
                ('purchase_cost', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription_plan.subscription_plan_details')),
            ],
        ),
    ]
