# Generated by Django 3.1.4 on 2021-05-12 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0006_merchant_subscriptions_recharge_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_subscriptions_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
