# Generated by Django 3.1.4 on 2021-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0007_merchant_subscriptions_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='business_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='plan_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='business_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='plan_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='merchant_subscriptions',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recharge_history',
            name='subscription_plan_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
