# Generated by Django 3.1.4 on 2021-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0008_auto_20210524_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant_subscriptions',
            old_name='business_id',
            new_name='subscription_name',
        ),
        migrations.RenameField(
            model_name='recharge_history',
            old_name='business_id',
            new_name='business_ids',
        ),
        migrations.RemoveField(
            model_name='merchant_subscriptions',
            name='digital_bill',
        ),
        migrations.RemoveField(
            model_name='merchant_subscriptions',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='recharge_history',
            name='digital_bill',
        ),
        migrations.RemoveField(
            model_name='recharge_history',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='business_ids',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='per_cash_memo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='per_digital_bill_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='per_digital_cash_memo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='per_digital_receipt_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='per_receipt_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='is_promotional_sms_plan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='per_cash_memo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='per_digital_bill_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='per_digital_cash_memo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='per_digital_receipt_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='per_receipt_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchant_subscriptions',
            name='per_bill_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recharge_history',
            name='per_bill_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
