# Generated by Django 3.1.4 on 2021-05-31 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_subscription', '0011_auto_20210530_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge_history',
            name='per_sms_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='total_sms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='merchant_bulk_sms_subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=500, null=True)),
                ('subscription_name', models.CharField(blank=True, max_length=500, null=True)),
                ('business_ids', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_sms', models.CharField(blank=True, max_length=100, null=True)),
                ('per_sms_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('total_sms_avilable', models.FloatField(blank=True, null=True)),
                ('purchase_cost', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
