# Generated by Django 3.1.4 on 2021-06-08 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0012_auto_20210531_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='sent_bill_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('mobile_no', models.CharField(blank=True, default='', max_length=100)),
                ('m_business_id', models.CharField(blank=True, default='', max_length=200)),
                ('green_bill_transaction', models.BooleanField(default=False)),
                ('green_bill_print_transaction', models.BooleanField(default=False)),
                ('print_transaction', models.BooleanField(default=False)),
                ('digital_bill', models.BooleanField(default=False)),
                ('sms_bill', models.BooleanField(default=False)),
                ('bill_amount', models.CharField(blank=True, max_length=100)),
                ('bill_cost', models.CharField(blank=True, max_length=100)),
                ('merchant_bill', models.BooleanField(default=False)),
                ('customer_bill', models.BooleanField(default=False)),
                ('parking_bill', models.BooleanField(default=False)),
                ('petrol_bill', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
