# Generated by Django 3.1.4 on 2021-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0013_sent_bill_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='recharge_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
