# Generated by Django 3.1.4 on 2021-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0015_auto_20210612_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_bulk_sms_subscriptions',
            name='payu_transaction_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='merchant_bulk_sms_subscriptions',
            name='transcation_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='payu_transaction_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='transcation_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='merchant_subscriptions',
            name='payu_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchant_subscriptions',
            name='transcation_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
