# Generated by Django 3.1.4 on 2021-06-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0016_auto_20210612_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant_subscriptions',
            old_name='transcation_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='merchant_bulk_sms_subscriptions',
            name='transcation_id',
        ),
        migrations.RemoveField(
            model_name='recharge_history',
            name='transcation_id',
        ),
        migrations.AddField(
            model_name='merchant_bulk_sms_subscriptions',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchant_bulk_sms_subscriptions',
            name='payu_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recharge_history',
            name='payu_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
