# Generated by Django 3.1.4 on 2021-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0021_auto_20210625_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge_history',
            name='bank_transaction_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
