# Generated by Django 3.1.4 on 2021-07-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0022_recharge_history_bank_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_for_subscriptions_requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('contact_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_requirements', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
