# Generated by Django 3.1.4 on 2021-07-15 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0023_contact_for_subscriptions_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_for_subscriptions_requirements',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
