# Generated by Django 3.1.4 on 2021-07-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0024_contact_for_subscriptions_requirements_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_for_subscriptions_requirements',
            name='subscription_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
