# Generated by Django 3.1.4 on 2021-07-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0025_contact_for_subscriptions_requirements_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='expired_plan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='one_month_expiry',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='one_week_expiry',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='promotional_sms_subscriptions',
            name='expired_plan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='promotional_sms_subscriptions',
            name='one_month_expiry',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='promotional_sms_subscriptions',
            name='one_week_expiry',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transactional_sms_subscriptions',
            name='expired_plan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transactional_sms_subscriptions',
            name='one_month_expiry',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transactional_sms_subscriptions',
            name='one_week_expiry',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
