# Generated by Django 3.1.4 on 2021-07-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0026_auto_20210727_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotional_sms_subscriptions',
            old_name='expired_plan',
            new_name='low_sms_balance',
        ),
        migrations.RenameField(
            model_name='transactional_sms_subscriptions',
            old_name='expired_plan',
            new_name='low_sms_balance',
        ),
        migrations.RemoveField(
            model_name='promotional_sms_subscriptions',
            name='one_month_expiry',
        ),
        migrations.RemoveField(
            model_name='promotional_sms_subscriptions',
            name='one_week_expiry',
        ),
        migrations.RemoveField(
            model_name='transactional_sms_subscriptions',
            name='one_month_expiry',
        ),
        migrations.RemoveField(
            model_name='transactional_sms_subscriptions',
            name='one_week_expiry',
        ),
    ]
