# Generated by Django 3.1.4 on 2021-08-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0027_auto_20210727_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='gst_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant_subscriptions',
            name='no_of_users',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='gst_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recharge_history',
            name='no_of_users',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
