# Generated by Django 3.1.4 on 2021-08-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_subscription', '0028_auto_20210811_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent_bill_history',
            name='is_exe',
            field=models.BooleanField(default=False),
        ),
    ]
