# Generated by Django 3.1.4 on 2021-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_info', '0004_merchantdisablereasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmailsmsmerchantmodel',
            name='receiver_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
