# Generated by Django 3.1.4 on 2020-12-10 19:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email_templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notification_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=500)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_super_admin_setting', models.BooleanField(default=False)),
                ('is_customer_setting', models.BooleanField(default=False)),
                ('is_merchant_setting', models.BooleanField(default=False)),
                ('is_partner_setting', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('send_app_notification', models.BooleanField(default=False)),
            ],
        ),
    ]
