# Generated by Django 3.1.4 on 2020-12-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_settings',
            name='send_app_notification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification_settings',
            name='send_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification_settings',
            name='send_sms',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
