# Generated by Django 3.1.4 on 2021-06-05 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_settings', '0005_greenpointssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenPointsEarnedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referent_mobile_no', models.CharField(default=0, max_length=20, null=True)),
                ('referral_mobile_no', models.CharField(default=0, max_length=20, null=True)),
                ('is_referral', models.BooleanField(default=False)),
                ('is_referent', models.BooleanField(default=False)),
                ('earned_green_points', models.CharField(default=0, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
