# Generated by Django 3.1.4 on 2021-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_settings', '0007_greenpointsearnedhistory_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_settings',
            name='is_app_notification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='notification_settings',
            name='is_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='notification_settings',
            name='is_sms',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
