# Generated by Django 3.1.4 on 2021-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_settings', '0008_auto_20210616_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageCompaniesDMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
