# Generated by Django 3.1.4 on 2021-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StampModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('stampdesgn', models.CharField(max_length=50)),
            ],
        ),
    ]
