# Generated by Django 3.1.4 on 2021-08-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20210817_1719'),
        ('merchant_stamp', '0002_merchantusagestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantusagestamp',
            name='merchant_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile'),
        ),
    ]
