# Generated by Django 3.1.4 on 2021-09-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_stamp', '0003_merchantusagestamp_merchant_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantusagestamp',
            name='is_check',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
