# Generated by Django 3.1.4 on 2021-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_stamp', '0006_selectstampimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectstampimage',
            name='m_select_image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
