# Generated by Django 3.1.4 on 2021-09-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merchantprofile_schedule_pdf_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_stamp', '0007_auto_20210913_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='usereceiptrstamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_image_id', models.CharField(max_length=50, null=True)),
                ('merchant_business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile')),
                ('merchant_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usecashmemostamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_image_id', models.CharField(max_length=50, null=True)),
                ('merchant_business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.merchantprofile')),
                ('merchant_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
