# Generated by Django 3.1.4 on 2021-09-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_stamp', '0009_merchant_receipt_upload_stamp_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='merchant_receipt_upload_stamp_img',
        ),
    ]
