# Generated by Django 3.1.4 on 2021-05-31 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner_my_subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner_subscriptions',
            old_name='plan_type',
            new_name='subscription_name',
        ),
        migrations.RemoveField(
            model_name='partner_recharge_history',
            name='digital_bill',
        ),
        migrations.RemoveField(
            model_name='partner_recharge_history',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='partner_subscriptions',
            name='digital_bill',
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='is_promotional_sms_plan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='per_cash_memo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='per_digital_bill_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='per_digital_cash_memo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='per_digital_receipt_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='per_receipt_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='per_sms_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='total_sms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='valid_for_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_subscriptions',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_subscriptions',
            name='per_cash_memo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_subscriptions',
            name='per_digital_bill_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_subscriptions',
            name='per_digital_cash_memo_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_subscriptions',
            name='per_digital_receipt_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_subscriptions',
            name='per_receipt_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_subscriptions',
            name='valid_for_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner_recharge_history',
            name='per_bill_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner_subscriptions',
            name='per_bill_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='partner_bulk_sms_subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=500, null=True)),
                ('subscription_name', models.CharField(blank=True, max_length=500, null=True)),
                ('total_sms', models.CharField(blank=True, max_length=100, null=True)),
                ('per_sms_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('total_sms_avilable', models.FloatField(blank=True, null=True)),
                ('purchase_cost', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('partner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
