# Generated by Django 3.1.4 on 2021-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_my_subscription', '0002_auto_20210531_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_subscriptions',
            name='payu_transaction_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner_subscriptions',
            name='transcation_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
