# Generated by Django 3.1.4 on 2021-06-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_my_subscription', '0004_auto_20210612_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner_bulk_sms_subscriptions',
            old_name='transcation_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='partner_recharge_history',
            old_name='transcation_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='partner_subscriptions',
            old_name='transcation_id',
            new_name='transaction_id',
        ),
    ]
