# Generated by Django 3.1.4 on 2021-06-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_my_subscription', '0007_auto_20210615_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_recharge_history',
            name='invoice_no',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
