# Generated by Django 3.1.4 on 2021-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_my_subscription', '0009_auto_20210624_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_subscriptions',
            name='recharge_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
