# Generated by Django 3.1.4 on 2021-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_my_subscription', '0011_auto_20211005_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner_subscriptions',
            name='b_transaction_id',
        ),
        migrations.RemoveField(
            model_name='partner_subscriptions',
            name='check_no',
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='bank_transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='cheque_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner_recharge_history',
            name='mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
