# Generated by Django 3.1.4 on 2021-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_apis', '0003_customerqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerqr',
            name='qr_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
