# Generated by Django 3.1.4 on 2022-01-31 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_apis', '0005_auto_20210129_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyeltypoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyeltyPoints', models.CharField(max_length=100, null=True)),
                ('mobile_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
