# Generated by Django 3.1.4 on 2021-06-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0026_auto_20210605_1327'),
        ('category_and_tags', '0002_bill_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=20)),
                ('device_id', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('bill', models.ImageField(blank=True, default='', null=True, upload_to='merchant_bill')),
                ('bill_received_business_name', models.CharField(blank=True, default='', max_length=200)),
                ('bill_amount', models.FloatField(blank=True, default=0, null=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('customer_added', models.BooleanField(default=False)),
                ('bill_tags', models.CharField(blank=True, default='', max_length=20000, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('custom_business_name', models.CharField(blank=True, default='', max_length=200)),
                ('bill_url', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('seen_status', models.BooleanField(default=False)),
                ('reject_status', models.BooleanField(default=False)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=500)),
                ('business_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.merchantprofile')),
                ('customer_bill_category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='category_and_tags.bill_category')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('bill', models.ImageField(blank=True, default='', null=True, upload_to='customer_bill')),
                ('bill_amount', models.FloatField(blank=True, default=0, null=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('customer_added', models.BooleanField(default=False)),
                ('bill_tags', models.CharField(blank=True, default='', max_length=20000, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('custom_business_name', models.CharField(blank=True, default='', max_length=200)),
                ('bill_url', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('green_points_earned', models.CharField(blank=True, max_length=10, null=True)),
                ('seen_status', models.BooleanField(default=False)),
                ('reject_status', models.BooleanField(default=False)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=500)),
                ('business_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.merchantprofile')),
                ('customer_bill_category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='category_and_tags.bill_category')),
                ('mobile_no', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
