# Generated by Django 3.1.4 on 2021-06-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantbill',
            name='temp',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
