# Generated by Django 3.1.4 on 2021-06-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0002_merchantbill_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantbill',
            name='temp',
        ),
    ]
