# Generated by Django 3.1.4 on 2021-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0003_remove_merchantbill_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberCustomerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('m_user_id', models.CharField(blank=True, max_length=100)),
                ('m_business_id', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceNumberMerchantBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('m_user_id', models.CharField(blank=True, max_length=100)),
                ('m_business_id', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customerbill',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
