# Generated by Django 3.1.4 on 2021-06-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0004_auto_20210608_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceNumberMerchantBill',
            new_name='InvoiceNumberSoftwareBill',
        ),
        migrations.DeleteModel(
            name='InvoiceNumberCustomerBill',
        ),
    ]
