# Generated by Django 3.1.4 on 2021-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0007_auto_20210608_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='feedback_question',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='feedback_selected_option',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='feedback_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='feedback_question',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='feedback_selected_option',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='feedback_submit',
            field=models.BooleanField(default=False),
        ),
    ]
