# Generated by Django 3.1.4 on 2021-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0008_auto_20210609_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
