# Generated by Django 3.1.4 on 2021-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0009_auto_20210609_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='feedback_reply',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
