# Generated by Django 3.1.4 on 2021-06-16 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_merchantprofile_by_partner'),
        ('merchant_software_apis', '0010_customerbill_feedback_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='partner_business_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.partnerprofile'),
        ),
    ]
