# Generated by Django 3.1.4 on 2021-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0012_auto_20210619_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
