# Generated by Django 3.1.4 on 2021-07-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0013_customerbill_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='bill_tags',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
