# Generated by Django 3.1.4 on 2021-08-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0014_auto_20210724_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='is_exe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='is_exe',
            field=models.BooleanField(default=False),
        ),
    ]
