# Generated by Django 3.1.4 on 2021-08-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0015_auto_20210814_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbill',
            name='is_exe',
        ),
        migrations.RemoveField(
            model_name='merchantbill',
            name='is_exe',
        ),
    ]
