# Generated by Django 3.1.4 on 2021-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0016_auto_20210814_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='stamp_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='stamp_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
