# Generated by Django 3.1.4 on 2021-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0018_auto_20210927_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='exe_bill_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='exe_bill_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
