# Generated by Django 3.1.4 on 2021-10-01 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0019_auto_20210930_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExePrintStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=20)),
                ('bill', models.ImageField(blank=True, default='', null=True, upload_to='customer_bill')),
                ('bill_date', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
