# Generated by Django 3.1.4 on 2021-10-01 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0020_exeprintstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exeprintstatus',
            name='bill_date',
        ),
        migrations.AddField(
            model_name='exeprintstatus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
