# Generated by Django 3.1.4 on 2021-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0021_auto_20211001_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=20)),
                ('bill', models.ImageField(blank=True, default='', null=True, upload_to='customer_bill')),
            ],
        ),
    ]
