# Generated by Django 3.1.4 on 2021-10-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0022_exeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='greenbill_digital_bill',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='greenbill_sms_bill',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='greenbill_digital_bill',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='greenbill_sms_bill',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
