# Generated by Django 3.1.4 on 2021-10-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0025_auto_20211020_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='is_ciprone',
            field=models.BooleanField(default=False),
        ),
    ]
