# Generated by Django 3.1.4 on 2021-10-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0026_customerbill_is_ciprone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='delete_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='delete_bill',
            field=models.BooleanField(default=False),
        ),
    ]
