# Generated by Django 3.1.4 on 2021-11-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0030_auto_20211108_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='particular',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
