# Generated by Django 3.1.4 on 2021-11-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0031_customerbill_particular'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='card',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='cash',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='digital_pay',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
