# Generated by Django 3.1.4 on 2021-11-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0032_auto_20211108_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='cgst',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='discount_in_percentage',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='hsn',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='igst',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='pack',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='sgst',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='transport_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='truck_driver',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='truck_license_no',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='truck_no',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
