# Generated by Django 3.1.4 on 2021-11-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0033_auto_20211109_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='maximum_retail_price',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
