# Generated by Django 3.1.4 on 2021-11-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0034_customerbill_maximum_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='net_amount',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='total_amount',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
