# Generated by Django 3.1.4 on 2021-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0037_auto_20211115_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='bar_details',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerbill',
            name='food_details',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
