# Generated by Django 3.1.4 on 2021-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0039_auto_20211116_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='is_checkoutpin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantbill',
            name='is_checkoutpin',
            field=models.BooleanField(default=False),
        ),
    ]
