# Generated by Django 3.1.4 on 2022-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0040_auto_20211117_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='xyz',
            field=models.CharField(default='', max_length=100),
        ),
    ]
