# Generated by Django 3.1.4 on 2022-01-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0041_customerbill_xyz'),
    ]

    operations = [
        migrations.CreateModel(
            name='habronsendbillapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(default='', max_length=100)),
                ('nabe', models.CharField(default='', max_length=2999)),
            ],
        ),
    ]
