# Generated by Django 3.1.4 on 2022-01-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0042_habronsendbillapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='habronsendbillapi',
        ),
    ]
