# Generated by Django 3.1.4 on 2022-01-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0044_auto_20220119_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='item_details',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
