# Generated by Django 3.1.4 on 2022-01-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0045_customerbill_item_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbill',
            name='bill_discount',
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='bill_gross_amount',
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='food_description',
        ),
        migrations.RemoveField(
            model_name='customerbill',
            name='food_mrp',
        ),
    ]
