# Generated by Django 3.1.4 on 2022-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0051_auto_20220119_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
