# Generated by Django 3.1.4 on 2022-04-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_software_apis', '0052_auto_20220119_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
