# Generated by Django 3.1.4 on 2021-08-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_payment', '0003_auto_20210806_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlinks',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlinks',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlinks',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
