# Generated by Django 3.1.4 on 2021-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_stamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wstampmodels',
            name='is_check',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
