# Generated by Django 3.1.4 on 2021-11-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_stamp', '0002_wstampmodels_is_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantDeletedStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_business_id', models.CharField(default='', max_length=100, null=True)),
                ('deleted_stamp_id', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
