# Generated by Django 3.1.4 on 2021-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_design', '0004_authorised_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_designs',
            name='pay_link',
            field=models.BooleanField(default=False),
        ),
    ]
