# Generated by Django 3.1.4 on 2021-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest_a_brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestbrand',
            name='contact_no',
            field=models.CharField(default=7709977701, max_length=100),
            preserve_default=False,
        ),
    ]
