# Generated by Django 3.1.4 on 2021-05-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest_a_brand', '0002_suggestbrand_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestbrand',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suggestbrand',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
