# Generated by Django 3.1.4 on 2021-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest_a_brand', '0003_auto_20210518_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestbrand',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
