# Generated by Django 3.1.4 on 2021-06-15 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0003_smsheadermodel_templatecontentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsheadermodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='templatecontentmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
