# Generated by Django 3.1.4 on 2021-06-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0004_auto_20210615_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='promotional',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='transactional',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
