# Generated by Django 3.1.4 on 2021-06-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0005_auto_20210616_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='promotional',
        ),
        migrations.AddField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='sent_status',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
