# Generated by Django 3.1.4 on 2021-07-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0006_auto_20210616_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='customer_area',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='customer_city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='customer_state',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
