# Generated by Django 3.1.4 on 2021-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0007_auto_20210703_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsheadermodel',
            name='Active_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='templatecontentmodel',
            name='Active_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
