# Generated by Django 3.1.4 on 2021-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0008_auto_20210713_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecontentmodel',
            name='sms_header',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
