# Generated by Django 3.1.4 on 2021-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0009_templatecontentmodel_sms_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecontentmodel',
            name='template_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
