# Generated by Django 3.1.4 on 2021-08-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0010_templatecontentmodel_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='sms_count',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
