# Generated by Django 3.1.4 on 2021-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0011_bulkmailsmsmerchantcustomermodel_sms_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsheadermodel',
            name='header_type',
            field=models.CharField(default='Transactional', max_length=50),
        ),
    ]
