# Generated by Django 3.1.4 on 2021-12-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_promotion', '0012_smsheadermodel_header_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmailsmsmerchantcustomermodel',
            name='campaign_name',
            field=models.CharField(default='Test Campaign', max_length=500),
        ),
    ]
