# Generated by Django 3.1.4 on 2021-06-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_amount_per_refferal', models.CharField(default=0, max_length=150, null=True)),
                ('recharge_amount_per_referent', models.CharField(default=0, max_length=150, null=True)),
            ],
        ),
    ]
