# Generated by Django 3.1.4 on 2021-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referent_mobile_no', models.CharField(default=0, max_length=20, null=True)),
                ('referral_mobile_no', models.CharField(default=0, max_length=20, null=True)),
                ('is_referral', models.BooleanField(default=False)),
                ('is_referent', models.BooleanField(default=False)),
                ('earned_rechage_points', models.CharField(default=0, max_length=100, null=True)),
            ],
        ),
    ]
