# Generated by Django 3.1.4 on 2021-06-05 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('referral_points', '0002_referralhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralhistory',
            old_name='earned_rechage_points',
            new_name='earned_recharge_points',
        ),
        migrations.AddField(
            model_name='referralhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
