# Generated by Django 3.1.4 on 2021-04-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ads_below_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buniness_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('suggested_business_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('adress', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_parking', models.BooleanField(default=False, null=True)),
                ('is_petrol', models.BooleanField(default=False, null=True)),
                ('is_other', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
