# Generated by Django 3.1.4 on 2021-04-20 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads_below_bill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
