# Generated by Django 3.1.4 on 2021-04-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0003_auto_20210420_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestbusiness',
            old_name='buniness_id',
            new_name='business_id',
        ),
    ]
