# Generated by Django 3.1.4 on 2021-04-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0004_auto_20210420_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestbusiness',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='suggestbusiness',
            old_name='business_id',
            new_name='m_business_id',
        ),
    ]
