# Generated by Django 3.1.4 on 2021-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0005_auto_20210420_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestbusiness',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
