# Generated by Django 3.1.4 on 2021-07-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0006_auto_20210708_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestbusiness',
            name='contact_no',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
