# Generated by Django 3.1.5 on 2021-03-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports_faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=1000, null=True)),
                ('module_name', models.CharField(default='', max_length=1000, null=True)),
                ('video_url', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
