# Generated by Django 3.1.5 on 2021-03-01 07:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports_faq', '0003_faqs_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=1000, null=True)),
                ('module_name', models.CharField(default='', max_length=1000, null=True)),
                ('blog', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
