# Generated by Django 3.1.4 on 2021-05-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports_faq', '0006_video_model_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs_model',
            old_name='quation',
            new_name='question',
        ),
    ]
