# Generated by Django 3.1.4 on 2021-05-20 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supports_faq', '0007_auto_20210512_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs_model',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faqs_model',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video_model',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
